"""
Auto-generated Python bindings for bbknn

Source: scl/binding/c_api/bbknn.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_bbknn_compute_norms(struct scl_sparse_matrix * matrix, scl_real_t * norms_sq, int n_cells)
_lib.scl_bbknn_compute_norms.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_int]
_lib.scl_bbknn_compute_norms.restype = c_int

def scl_bbknn_compute_norms(matrix, norms_sq, n_cells):
    """
     @brief Precompute squared L2 norms for each cell (optimization)
 @param[in] matrix Expression matrix (non-null)
 @param[out] norms_sq Squared norms [n_cells] (non-null)
 @param[in] n_cells Number of cells
 @return SCL_OK on success, error code otherwise
 @note Use this for repeated BBKNN calls on same matrix
    
    Args:
        matrix: struct scl_sparse_matrix *
        norms_sq: scl_real_t *
        n_cells: int
    
    Returns:
        int
    """
    return _lib.scl_bbknn_compute_norms(matrix, norms_sq, n_cells)


# C: int scl_bbknn(struct scl_sparse_matrix * matrix, const int32_t * batch_labels, int n_cells, int n_batches, int k, scl_index_t * out_indices, scl_real_t * out_distances)
_lib.scl_bbknn.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, c_int, c_int, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_bbknn.restype = c_int

def scl_bbknn(matrix, batch_labels, n_cells, n_batches, k, out_indices, out_distances):
    """
     @brief Compute batch-balanced KNN graph
 @param[in] matrix Expression matrix (cells x genes) (non-null)
 @param[in] batch_labels Batch assignment [n_cells] (non-null)
 @param[in] n_cells Number of cells
 @param[in] n_batches Number of batches
 @param[in] k Neighbors per batch
 @param[out] out_indices Neighbor indices [n_cells * n_batches * k] (non-null)
 @param[out] out_distances Neighbor distances [n_cells * n_batches * k] (non-null)
 @return SCL_OK on success, error code otherwise
 @details For each cell i:
   - Finds k nearest neighbors in batch 0 -> out[i*n_batches*k + 0*k : 1*k]
   - Finds k nearest neighbors in batch 1 -> out[i*n_batches*k + 1*k : 2*k]
   - ...
   - Total neighbors per cell: n_batches * k
 @note Distance metric: Euclidean (L2)
 @note Caller must pre-allocate output arrays
 @note Automatically parallelized over cells
    
    Args:
        matrix: struct scl_sparse_matrix *
        batch_labels: const int32_t *
        n_cells: int
        n_batches: int
        k: int
        out_indices: scl_index_t *
        out_distances: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_bbknn(matrix, batch_labels, n_cells, n_batches, k, out_indices, out_distances)


# C: int scl_bbknn_with_norms(struct scl_sparse_matrix * matrix, const int32_t * batch_labels, int n_cells, int n_batches, int k, const scl_real_t * norms_sq, scl_index_t * out_indices, scl_real_t * out_distances)
_lib.scl_bbknn_with_norms.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, c_int, c_int, POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_bbknn_with_norms.restype = c_int

def scl_bbknn_with_norms(matrix, batch_labels, n_cells, n_batches, k, norms_sq, out_indices, out_distances):
    """
     @brief BBKNN with precomputed norms (faster for repeated calls)
 @param[in] matrix Expression matrix (non-null)
 @param[in] batch_labels Batch assignment [n_cells] (non-null)
 @param[in] n_cells Number of cells
 @param[in] n_batches Number of batches
 @param[in] k Neighbors per batch
 @param[in] norms_sq Precomputed squared norms [n_cells] (non-null)
 @param[out] out_indices Neighbor indices (non-null)
 @param[out] out_distances Neighbor distances (non-null)
 @return SCL_OK on success, error code otherwise
 @note Use scl_bbknn_compute_norms() first to precompute norms
 @note Skips norm computation (faster for multiple BBKNN calls)
    
    Args:
        matrix: struct scl_sparse_matrix *
        batch_labels: const int32_t *
        n_cells: int
        n_batches: int
        k: int
        norms_sq: const scl_real_t *
        out_indices: scl_index_t *
        out_distances: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_bbknn_with_norms(matrix, batch_labels, n_cells, n_batches, k, norms_sq, out_indices, out_distances)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_bbknn",
    "scl_bbknn_compute_norms",
    "scl_bbknn_with_norms",
]