"""
Auto-generated Python bindings for communication

Source: scl/binding/c_api/communication.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_comm_score_method_t:
    """C enum: scl_comm_score_method_t"""
    SCL_COMM_SCORE_MEAN_PRODUCT = 0
    SCL_COMM_SCORE_GEOMETRIC_MEAN = 1
    SCL_COMM_SCORE_MIN_MEAN = 2
    SCL_COMM_SCORE_PRODUCT = 3
    SCL_COMM_SCORE_NATMI = 4

class scl_comm_score_method_t:
    """C enum: scl_comm_score_method_t"""
    SCL_COMM_SCORE_MEAN_PRODUCT = 0
    SCL_COMM_SCORE_GEOMETRIC_MEAN = 1
    SCL_COMM_SCORE_MIN_MEAN = 2
    SCL_COMM_SCORE_PRODUCT = 3
    SCL_COMM_SCORE_NATMI = 4

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_comm_score_method_t = c_void_p  # typedef enum scl_comm_score_method_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_comm_lr_score_matrix(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, long ligand_gene, long receptor_gene, long n_cells, long n_types, scl_real_t * score_matrix, scl_comm_score_method_t method)
_lib.scl_comm_lr_score_matrix.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, c_long, POINTER(c_void_p), c_void_p]
_lib.scl_comm_lr_score_matrix.restype = c_int

def scl_comm_lr_score_matrix(expression, cell_type_labels, ligand_gene, receptor_gene, n_cells, n_types, score_matrix, method):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_gene: long
        receptor_gene: long
        n_cells: long
        n_types: long
        score_matrix: scl_real_t *
        method: scl_comm_score_method_t
    
    Returns:
        int
    """
    return _lib.scl_comm_lr_score_matrix(expression, cell_type_labels, ligand_gene, receptor_gene, n_cells, n_types, score_matrix, method)


# C: int scl_comm_lr_score_batch(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, const scl_index_t * ligand_genes, const scl_index_t * receptor_genes, long n_pairs, long n_cells, long n_types, scl_real_t * scores, scl_comm_score_method_t method)
_lib.scl_comm_lr_score_batch.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p), c_void_p]
_lib.scl_comm_lr_score_batch.restype = c_int

def scl_comm_lr_score_batch(expression, cell_type_labels, ligand_genes, receptor_genes, n_pairs, n_cells, n_types, scores, method):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_genes: const scl_index_t *
        receptor_genes: const scl_index_t *
        n_pairs: long
        n_cells: long
        n_types: long
        scores: scl_real_t *
        method: scl_comm_score_method_t
    
    Returns:
        int
    """
    return _lib.scl_comm_lr_score_batch(expression, cell_type_labels, ligand_genes, receptor_genes, n_pairs, n_cells, n_types, scores, method)


# C: int scl_comm_lr_permutation_test(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, long ligand_gene, long receptor_gene, long sender_type, long receiver_type, long n_cells, long n_permutations, scl_real_t * observed_score, scl_real_t * p_value, scl_comm_score_method_t method, unsigned long seed)
_lib.scl_comm_lr_permutation_test.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, c_long, c_long, c_long, POINTER(c_void_p), POINTER(c_void_p), c_void_p, c_ulong]
_lib.scl_comm_lr_permutation_test.restype = c_int

def scl_comm_lr_permutation_test(expression, cell_type_labels, ligand_gene, receptor_gene, sender_type, receiver_type, n_cells, n_permutations, observed_score, p_value, method, seed):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_gene: long
        receptor_gene: long
        sender_type: long
        receiver_type: long
        n_cells: long
        n_permutations: long
        observed_score: scl_real_t *
        p_value: scl_real_t *
        method: scl_comm_score_method_t
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_comm_lr_permutation_test(expression, cell_type_labels, ligand_gene, receptor_gene, sender_type, receiver_type, n_cells, n_permutations, observed_score, p_value, method, seed)


# C: int scl_comm_probability(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, const scl_index_t * ligand_genes, const scl_index_t * receptor_genes, long n_pairs, long n_cells, long n_types, scl_real_t * p_values, scl_real_t * scores, long n_permutations, scl_comm_score_method_t method, unsigned long seed)
_lib.scl_comm_probability.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p), POINTER(c_void_p), c_long, c_void_p, c_ulong]
_lib.scl_comm_probability.restype = c_int

def scl_comm_probability(expression, cell_type_labels, ligand_genes, receptor_genes, n_pairs, n_cells, n_types, p_values, scores, n_permutations, method, seed):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_genes: const scl_index_t *
        receptor_genes: const scl_index_t *
        n_pairs: long
        n_cells: long
        n_types: long
        p_values: scl_real_t *
        scores: scl_real_t *
        n_permutations: long
        method: scl_comm_score_method_t
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_comm_probability(expression, cell_type_labels, ligand_genes, receptor_genes, n_pairs, n_cells, n_types, p_values, scores, n_permutations, method, seed)


# C: int scl_comm_filter_significant(const scl_real_t * p_values, long n_pairs, long n_types, double p_threshold, scl_index_t * pair_indices, scl_index_t * sender_types, scl_index_t * receiver_types, scl_real_t * filtered_pvalues, long max_results, scl_index_t * n_results)
_lib.scl_comm_filter_significant.argtypes = [POINTER(c_void_p), c_long, c_long, c_double, POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_long, POINTER(c_void_p)]
_lib.scl_comm_filter_significant.restype = c_int

def scl_comm_filter_significant(p_values, n_pairs, n_types, p_threshold, pair_indices, sender_types, receiver_types, filtered_pvalues, max_results, n_results):
    """
    Args:
        p_values: const scl_real_t *
        n_pairs: long
        n_types: long
        p_threshold: double
        pair_indices: scl_index_t *
        sender_types: scl_index_t *
        receiver_types: scl_index_t *
        filtered_pvalues: scl_real_t *
        max_results: long
        n_results: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_filter_significant(p_values, n_pairs, n_types, p_threshold, pair_indices, sender_types, receiver_types, filtered_pvalues, max_results, n_results)


# C: int scl_comm_aggregate_to_network(const scl_real_t * scores, const scl_real_t * p_values, long n_pairs, long n_types, double p_threshold, scl_real_t * network_weights, scl_index_t * network_counts)
_lib.scl_comm_aggregate_to_network.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_double, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comm_aggregate_to_network.restype = c_int

def scl_comm_aggregate_to_network(scores, p_values, n_pairs, n_types, p_threshold, network_weights, network_counts):
    """
    Args:
        scores: const scl_real_t *
        p_values: const scl_real_t *
        n_pairs: long
        n_types: long
        p_threshold: double
        network_weights: scl_real_t *
        network_counts: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_aggregate_to_network(scores, p_values, n_pairs, n_types, p_threshold, network_weights, network_counts)


# C: int scl_comm_sender_score(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, const scl_index_t * ligand_genes, long n_ligands, long n_cells, long n_types, scl_real_t * scores)
_lib.scl_comm_sender_score.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p)]
_lib.scl_comm_sender_score.restype = c_int

def scl_comm_sender_score(expression, cell_type_labels, ligand_genes, n_ligands, n_cells, n_types, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_genes: const scl_index_t *
        n_ligands: long
        n_cells: long
        n_types: long
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_sender_score(expression, cell_type_labels, ligand_genes, n_ligands, n_cells, n_types, scores)


# C: int scl_comm_receiver_score(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, const scl_index_t * receptor_genes, long n_receptors, long n_cells, long n_types, scl_real_t * scores)
_lib.scl_comm_receiver_score.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p)]
_lib.scl_comm_receiver_score.restype = c_int

def scl_comm_receiver_score(expression, cell_type_labels, receptor_genes, n_receptors, n_cells, n_types, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        receptor_genes: const scl_index_t *
        n_receptors: long
        n_cells: long
        n_types: long
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_receiver_score(expression, cell_type_labels, receptor_genes, n_receptors, n_cells, n_types, scores)


# C: int scl_comm_network_centrality(const scl_real_t * network_weights, long n_types, scl_real_t * in_degree, scl_real_t * out_degree, scl_real_t * betweenness)
_lib.scl_comm_network_centrality.argtypes = [POINTER(c_void_p), c_long, POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comm_network_centrality.restype = c_int

def scl_comm_network_centrality(network_weights, n_types, in_degree, out_degree, betweenness):
    """
    Args:
        network_weights: const scl_real_t *
        n_types: long
        in_degree: scl_real_t *
        out_degree: scl_real_t *
        betweenness: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_network_centrality(network_weights, n_types, in_degree, out_degree, betweenness)


# C: int scl_comm_spatial_score(struct scl_sparse_matrix * expression, struct scl_sparse_matrix * spatial_graph, long ligand_gene, long receptor_gene, long n_cells, scl_real_t * cell_scores)
_lib.scl_comm_spatial_score.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p)]
_lib.scl_comm_spatial_score.restype = c_int

def scl_comm_spatial_score(expression, spatial_graph, ligand_gene, receptor_gene, n_cells, cell_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        spatial_graph: struct scl_sparse_matrix *
        ligand_gene: long
        receptor_gene: long
        n_cells: long
        cell_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_spatial_score(expression, spatial_graph, ligand_gene, receptor_gene, n_cells, cell_scores)


# C: int scl_comm_expression_specificity(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, long gene, long n_cells, long n_types, scl_real_t * specificity)
_lib.scl_comm_expression_specificity.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_void_p)]
_lib.scl_comm_expression_specificity.restype = c_int

def scl_comm_expression_specificity(expression, cell_type_labels, gene, n_cells, n_types, specificity):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        gene: long
        n_cells: long
        n_types: long
        specificity: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_expression_specificity(expression, cell_type_labels, gene, n_cells, n_types, specificity)


# C: int scl_comm_natmi_edge_weight(struct scl_sparse_matrix * expression, const scl_index_t * cell_type_labels, long ligand_gene, long receptor_gene, long n_cells, long n_types, scl_real_t * edge_weights)
_lib.scl_comm_natmi_edge_weight.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, c_long, c_long, POINTER(c_void_p)]
_lib.scl_comm_natmi_edge_weight.restype = c_int

def scl_comm_natmi_edge_weight(expression, cell_type_labels, ligand_gene, receptor_gene, n_cells, n_types, edge_weights):
    """
    Args:
        expression: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        ligand_gene: long
        receptor_gene: long
        n_cells: long
        n_types: long
        edge_weights: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comm_natmi_edge_weight(expression, cell_type_labels, ligand_gene, receptor_gene, n_cells, n_types, edge_weights)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_comm_aggregate_to_network",
    "scl_comm_expression_specificity",
    "scl_comm_filter_significant",
    "scl_comm_lr_permutation_test",
    "scl_comm_lr_score_batch",
    "scl_comm_lr_score_matrix",
    "scl_comm_natmi_edge_weight",
    "scl_comm_network_centrality",
    "scl_comm_probability",
    "scl_comm_receiver_score",
    "scl_comm_score_method_t",
    "scl_comm_score_method_t",
    "scl_comm_score_method_t",
    "scl_comm_sender_score",
    "scl_comm_spatial_score",
]