"""
Auto-generated Python bindings for comparison

Source: scl/binding/c_api/comparison.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_comp_composition_analysis(const scl_index_t * cell_types, const scl_index_t * conditions, int n_cells, int n_types, int n_conditions, scl_real_t * proportions, scl_real_t * p_values)
_lib.scl_comp_composition_analysis.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_int, c_int, c_int, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comp_composition_analysis.restype = c_int

def scl_comp_composition_analysis(cell_types, conditions, n_cells, n_types, n_conditions, proportions, p_values):
    """
    Args:
        cell_types: const scl_index_t *
        conditions: const scl_index_t *
        n_cells: int
        n_types: int
        n_conditions: int
        proportions: scl_real_t *
        p_values: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_composition_analysis(cell_types, conditions, n_cells, n_types, n_conditions, proportions, p_values)


# C: int scl_comp_abundance_test(const scl_index_t * cluster_labels, const scl_index_t * condition, int n_cells, scl_real_t * fold_changes, scl_real_t * p_values)
_lib.scl_comp_abundance_test.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_int, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comp_abundance_test.restype = c_int

def scl_comp_abundance_test(cluster_labels, condition, n_cells, fold_changes, p_values):
    """
    Args:
        cluster_labels: const scl_index_t *
        condition: const scl_index_t *
        n_cells: int
        fold_changes: scl_real_t *
        p_values: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_abundance_test(cluster_labels, condition, n_cells, fold_changes, p_values)


# C: int scl_comp_differential_abundance(const scl_index_t * cluster_labels, const scl_index_t * sample_ids, const scl_index_t * conditions, int n_cells, scl_real_t * da_scores, scl_real_t * p_values)
_lib.scl_comp_differential_abundance.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_void_p), c_int, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comp_differential_abundance.restype = c_int

def scl_comp_differential_abundance(cluster_labels, sample_ids, conditions, n_cells, da_scores, p_values):
    """
    Args:
        cluster_labels: const scl_index_t *
        sample_ids: const scl_index_t *
        conditions: const scl_index_t *
        n_cells: int
        da_scores: scl_real_t *
        p_values: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_differential_abundance(cluster_labels, sample_ids, conditions, n_cells, da_scores, p_values)


# C: int scl_comp_condition_response(struct scl_sparse_matrix * expression, const scl_index_t * conditions, int n_genes, scl_real_t * response_scores, scl_real_t * p_values)
_lib.scl_comp_condition_response.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_int, POINTER(c_void_p), POINTER(c_void_p)]
_lib.scl_comp_condition_response.restype = c_int

def scl_comp_condition_response(expression, conditions, n_genes, response_scores, p_values):
    """
    Args:
        expression: struct scl_sparse_matrix *
        conditions: const scl_index_t *
        n_genes: int
        response_scores: scl_real_t *
        p_values: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_condition_response(expression, conditions, n_genes, response_scores, p_values)


# C: int scl_comp_effect_size(const scl_real_t * group1, int n1, const scl_real_t * group2, int n2, scl_real_t * effect_size)
_lib.scl_comp_effect_size.argtypes = [POINTER(c_void_p), c_int, POINTER(c_void_p), c_int, POINTER(c_void_p)]
_lib.scl_comp_effect_size.restype = c_int

def scl_comp_effect_size(group1, n1, group2, n2, effect_size):
    """
    Args:
        group1: const scl_real_t *
        n1: int
        group2: const scl_real_t *
        n2: int
        effect_size: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_effect_size(group1, n1, group2, n2, effect_size)


# C: int scl_comp_glass_delta(const scl_real_t * control, int n_control, const scl_real_t * treatment, int n_treatment, scl_real_t * delta)
_lib.scl_comp_glass_delta.argtypes = [POINTER(c_void_p), c_int, POINTER(c_void_p), c_int, POINTER(c_void_p)]
_lib.scl_comp_glass_delta.restype = c_int

def scl_comp_glass_delta(control, n_control, treatment, n_treatment, delta):
    """
    Args:
        control: const scl_real_t *
        n_control: int
        treatment: const scl_real_t *
        n_treatment: int
        delta: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_glass_delta(control, n_control, treatment, n_treatment, delta)


# C: int scl_comp_hedges_g(const scl_real_t * group1, int n1, const scl_real_t * group2, int n2, scl_real_t * hedges_g)
_lib.scl_comp_hedges_g.argtypes = [POINTER(c_void_p), c_int, POINTER(c_void_p), c_int, POINTER(c_void_p)]
_lib.scl_comp_hedges_g.restype = c_int

def scl_comp_hedges_g(group1, n1, group2, n2, hedges_g):
    """
    Args:
        group1: const scl_real_t *
        n1: int
        group2: const scl_real_t *
        n2: int
        hedges_g: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_comp_hedges_g(group1, n1, group2, n2, hedges_g)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_comp_abundance_test",
    "scl_comp_composition_analysis",
    "scl_comp_condition_response",
    "scl_comp_differential_abundance",
    "scl_comp_effect_size",
    "scl_comp_glass_delta",
    "scl_comp_hedges_g",
]