"""
Auto-generated Python bindings for correlation

Source: scl/binding/c_api/correlation.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_corr_compute_stats(struct scl_sparse_matrix * matrix, scl_real_t * out_means, scl_real_t * out_inv_stds)
_lib.scl_corr_compute_stats.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double)]
_lib.scl_corr_compute_stats.restype = c_int

def scl_corr_compute_stats(matrix, out_means, out_inv_stds):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        out_means: scl_real_t *
        out_inv_stds: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_corr_compute_stats(matrix, out_means, out_inv_stds)


# C: int scl_corr_pearson(struct scl_sparse_matrix * matrix, const scl_real_t * means, const scl_real_t * inv_stds, scl_real_t * output)
_lib.scl_corr_pearson.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
_lib.scl_corr_pearson.restype = c_int

def scl_corr_pearson(matrix, means, inv_stds, output):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        means: const scl_real_t *
        inv_stds: const scl_real_t *
        output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_corr_pearson(matrix, means, inv_stds, output)


# C: int scl_corr_pearson_auto(struct scl_sparse_matrix * matrix, scl_real_t * output)
_lib.scl_corr_pearson_auto.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_corr_pearson_auto.restype = c_int

def scl_corr_pearson_auto(matrix, output):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_corr_pearson_auto(matrix, output)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_corr_compute_stats",
    "scl_corr_pearson",
    "scl_corr_pearson_auto",
]