"""
Auto-generated Python bindings for doublet

Source: scl/binding/c_api/doublet.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_doublet_method_t:
    """C enum: scl_doublet_method_t"""
    SCL_DOUBLET_METHOD_SCRUBLET = 0
    SCL_DOUBLET_METHOD_DOUBLETFINDER = 1
    SCL_DOUBLET_METHOD_HYBRID = 2

class scl_doublet_method_t:
    """C enum: scl_doublet_method_t"""
    SCL_DOUBLET_METHOD_SCRUBLET = 0
    SCL_DOUBLET_METHOD_DOUBLETFINDER = 1
    SCL_DOUBLET_METHOD_HYBRID = 2

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_doublet_method_t = c_void_p  # typedef enum scl_doublet_method_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_doublet_simulate_doublets(struct scl_sparse_matrix * X, long n_cells, long n_genes, long n_doublets, scl_real_t * doublet_profiles, unsigned long seed)
_lib.scl_doublet_simulate_doublets.argtypes = [POINTER(c_void_p), c_long, c_long, c_long, POINTER(c_double), c_ulong]
_lib.scl_doublet_simulate_doublets.restype = c_int

def scl_doublet_simulate_doublets(X, n_cells, n_genes, n_doublets, doublet_profiles, seed):
    """
    Args:
        X: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        n_doublets: long
        doublet_profiles: scl_real_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_doublet_simulate_doublets(X, n_cells, n_genes, n_doublets, doublet_profiles, seed)


# C: int scl_doublet_compute_knn_scores(struct scl_sparse_matrix * X, long n_cells, long n_genes, const scl_real_t * doublet_profiles, long n_doublets, long k_neighbors, scl_real_t * doublet_scores)
_lib.scl_doublet_compute_knn_scores.argtypes = [POINTER(c_void_p), c_long, c_long, POINTER(c_double), c_long, c_long, POINTER(c_double)]
_lib.scl_doublet_compute_knn_scores.restype = c_int

def scl_doublet_compute_knn_scores(X, n_cells, n_genes, doublet_profiles, n_doublets, k_neighbors, doublet_scores):
    """
    Args:
        X: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        doublet_profiles: const scl_real_t *
        n_doublets: long
        k_neighbors: long
        doublet_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_compute_knn_scores(X, n_cells, n_genes, doublet_profiles, n_doublets, k_neighbors, doublet_scores)


# C: int scl_doublet_compute_knn_scores_pca(const scl_real_t * cell_embeddings, long n_cells, long n_dims, const scl_real_t * doublet_embeddings, long n_doublets, long k_neighbors, scl_real_t * doublet_scores)
_lib.scl_doublet_compute_knn_scores_pca.argtypes = [POINTER(c_double), c_long, c_long, POINTER(c_double), c_long, c_long, POINTER(c_double)]
_lib.scl_doublet_compute_knn_scores_pca.restype = c_int

def scl_doublet_compute_knn_scores_pca(cell_embeddings, n_cells, n_dims, doublet_embeddings, n_doublets, k_neighbors, doublet_scores):
    """
    Args:
        cell_embeddings: const scl_real_t *
        n_cells: long
        n_dims: long
        doublet_embeddings: const scl_real_t *
        n_doublets: long
        k_neighbors: long
        doublet_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_compute_knn_scores_pca(cell_embeddings, n_cells, n_dims, doublet_embeddings, n_doublets, k_neighbors, doublet_scores)


# C: int scl_doublet_scrublet_scores(struct scl_sparse_matrix * X, long n_cells, long n_genes, scl_real_t * scores, long n_simulated, long k_neighbors, unsigned long seed)
_lib.scl_doublet_scrublet_scores.argtypes = [POINTER(c_void_p), c_long, c_long, POINTER(c_double), c_long, c_long, c_ulong]
_lib.scl_doublet_scrublet_scores.restype = c_int

def scl_doublet_scrublet_scores(X, n_cells, n_genes, scores, n_simulated, k_neighbors, seed):
    """
    Args:
        X: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        scores: scl_real_t *
        n_simulated: long
        k_neighbors: long
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_doublet_scrublet_scores(X, n_cells, n_genes, scores, n_simulated, k_neighbors, seed)


# C: int scl_doublet_doubletfinder_pann(const scl_real_t * cell_embeddings, long n_cells, long n_dims, const scl_real_t * doublet_embeddings, long n_doublets, double pK, scl_real_t * pann_scores)
_lib.scl_doublet_doubletfinder_pann.argtypes = [POINTER(c_double), c_long, c_long, POINTER(c_double), c_long, c_double, POINTER(c_double)]
_lib.scl_doublet_doubletfinder_pann.restype = c_int

def scl_doublet_doubletfinder_pann(cell_embeddings, n_cells, n_dims, doublet_embeddings, n_doublets, pK, pann_scores):
    """
    Args:
        cell_embeddings: const scl_real_t *
        n_cells: long
        n_dims: long
        doublet_embeddings: const scl_real_t *
        n_doublets: long
        pK: double
        pann_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_doubletfinder_pann(cell_embeddings, n_cells, n_dims, doublet_embeddings, n_doublets, pK, pann_scores)


# C: int scl_doublet_estimate_threshold(const scl_real_t * scores, int n_scores, double expected_doublet_rate, scl_real_t * threshold_out)
_lib.scl_doublet_estimate_threshold.argtypes = [POINTER(c_double), c_int, c_double, POINTER(c_double)]
_lib.scl_doublet_estimate_threshold.restype = c_int

def scl_doublet_estimate_threshold(scores, n_scores, expected_doublet_rate, threshold_out):
    """
    Args:
        scores: const scl_real_t *
        n_scores: int
        expected_doublet_rate: double
        threshold_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_estimate_threshold(scores, n_scores, expected_doublet_rate, threshold_out)


# C: int scl_doublet_call_doublets(const scl_real_t * scores, int n_scores, double threshold, int * is_doublet, scl_index_t * n_doublets_out)
_lib.scl_doublet_call_doublets.argtypes = [POINTER(c_double), c_int, c_double, POINTER(c_int), POINTER(c_int64)]
_lib.scl_doublet_call_doublets.restype = c_int

def scl_doublet_call_doublets(scores, n_scores, threshold, is_doublet, n_doublets_out):
    """
    Args:
        scores: const scl_real_t *
        n_scores: int
        threshold: double
        is_doublet: int *
        n_doublets_out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_call_doublets(scores, n_scores, threshold, is_doublet, n_doublets_out)


# C: int scl_doublet_detect_bimodal_threshold(const scl_real_t * scores, int n_scores, long n_bins, scl_real_t * threshold_out)
_lib.scl_doublet_detect_bimodal_threshold.argtypes = [POINTER(c_double), c_int, c_long, POINTER(c_double)]
_lib.scl_doublet_detect_bimodal_threshold.restype = c_int

def scl_doublet_detect_bimodal_threshold(scores, n_scores, n_bins, threshold_out):
    """
    Args:
        scores: const scl_real_t *
        n_scores: int
        n_bins: long
        threshold_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_detect_bimodal_threshold(scores, n_scores, n_bins, threshold_out)


# C: int scl_doublet_detect_doublets(struct scl_sparse_matrix * X, long n_cells, long n_genes, scl_real_t * scores, int * is_doublet, scl_doublet_method_t method, double expected_rate, long k_neighbors, unsigned long seed, scl_index_t * n_doublets_out)
_lib.scl_doublet_detect_doublets.argtypes = [POINTER(c_void_p), c_long, c_long, POINTER(c_double), POINTER(c_int), c_void_p, c_double, c_long, c_ulong, POINTER(c_int64)]
_lib.scl_doublet_detect_doublets.restype = c_int

def scl_doublet_detect_doublets(X, n_cells, n_genes, scores, is_doublet, method, expected_rate, k_neighbors, seed, n_doublets_out):
    """
    Args:
        X: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        scores: scl_real_t *
        is_doublet: int *
        method: scl_doublet_method_t
        expected_rate: double
        k_neighbors: long
        seed: unsigned long
        n_doublets_out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_detect_doublets(X, n_cells, n_genes, scores, is_doublet, method, expected_rate, k_neighbors, seed, n_doublets_out)


# C: int scl_doublet_get_singlet_indices(const int * is_doublet, int n_cells, scl_index_t * singlet_indices, int max_indices, scl_index_t * n_singlets_out)
_lib.scl_doublet_get_singlet_indices.argtypes = [POINTER(c_int), c_int, POINTER(c_int64), c_int, POINTER(c_int64)]
_lib.scl_doublet_get_singlet_indices.restype = c_int

def scl_doublet_get_singlet_indices(is_doublet, n_cells, singlet_indices, max_indices, n_singlets_out):
    """
    Args:
        is_doublet: const int *
        n_cells: int
        singlet_indices: scl_index_t *
        max_indices: int
        n_singlets_out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_get_singlet_indices(is_doublet, n_cells, singlet_indices, max_indices, n_singlets_out)


# C: int scl_doublet_score_stats(const scl_real_t * scores, int n_scores, scl_real_t * mean_out, scl_real_t * std_dev_out, scl_real_t * median_out)
_lib.scl_doublet_score_stats.argtypes = [POINTER(c_double), c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double)]
_lib.scl_doublet_score_stats.restype = c_int

def scl_doublet_score_stats(scores, n_scores, mean_out, std_dev_out, median_out):
    """
    Args:
        scores: const scl_real_t *
        n_scores: int
        mean_out: scl_real_t *
        std_dev_out: scl_real_t *
        median_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_doublet_score_stats(scores, n_scores, mean_out, std_dev_out, median_out)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_doublet_call_doublets",
    "scl_doublet_compute_knn_scores",
    "scl_doublet_compute_knn_scores_pca",
    "scl_doublet_detect_bimodal_threshold",
    "scl_doublet_detect_doublets",
    "scl_doublet_doubletfinder_pann",
    "scl_doublet_estimate_threshold",
    "scl_doublet_get_singlet_indices",
    "scl_doublet_method_t",
    "scl_doublet_method_t",
    "scl_doublet_method_t",
    "scl_doublet_score_stats",
    "scl_doublet_scrublet_scores",
    "scl_doublet_simulate_doublets",
]