"""
Auto-generated Python bindings for feature

Source: scl/binding/c_api/feature.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_feature_standard_moments(struct scl_sparse_matrix * matrix, scl_real_t * out_means, scl_real_t * out_vars, int n_features, int ddof)
_lib.scl_feature_standard_moments.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), c_int, c_int]
_lib.scl_feature_standard_moments.restype = c_int

def scl_feature_standard_moments(matrix, out_means, out_vars, n_features, ddof):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        out_means: scl_real_t *
        out_vars: scl_real_t *
        n_features: int
        ddof: int
    
    Returns:
        int
    """
    return _lib.scl_feature_standard_moments(matrix, out_means, out_vars, n_features, ddof)


# C: int scl_feature_clipped_moments(struct scl_sparse_matrix * matrix, const scl_real_t * clip_vals, scl_real_t * out_means, scl_real_t * out_vars, int n_features)
_lib.scl_feature_clipped_moments.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int]
_lib.scl_feature_clipped_moments.restype = c_int

def scl_feature_clipped_moments(matrix, clip_vals, out_means, out_vars, n_features):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        clip_vals: const scl_real_t *
        out_means: scl_real_t *
        out_vars: scl_real_t *
        n_features: int
    
    Returns:
        int
    """
    return _lib.scl_feature_clipped_moments(matrix, clip_vals, out_means, out_vars, n_features)


# C: int scl_feature_detection_rate(struct scl_sparse_matrix * matrix, scl_real_t * out_rates, int n_features)
_lib.scl_feature_detection_rate.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int]
_lib.scl_feature_detection_rate.restype = c_int

def scl_feature_detection_rate(matrix, out_rates, n_features):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        out_rates: scl_real_t *
        n_features: int
    
    Returns:
        int
    """
    return _lib.scl_feature_detection_rate(matrix, out_rates, n_features)


# C: int scl_feature_dispersion(const scl_real_t * means, const scl_real_t * vars, scl_real_t * out_dispersion, int n_features)
_lib.scl_feature_dispersion.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int]
_lib.scl_feature_dispersion.restype = c_int

def scl_feature_dispersion(means, vars, out_dispersion, n_features):
    """
    Args:
        means: const scl_real_t *
        vars: const scl_real_t *
        out_dispersion: scl_real_t *
        n_features: int
    
    Returns:
        int
    """
    return _lib.scl_feature_dispersion(means, vars, out_dispersion, n_features)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_feature_clipped_moments",
    "scl_feature_detection_rate",
    "scl_feature_dispersion",
    "scl_feature_standard_moments",
]