"""
Auto-generated Python bindings for gram

Source: scl/binding/c_api/gram.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_gram_compute(struct scl_sparse_matrix * matrix, scl_real_t * output, int n_rows)
_lib.scl_gram_compute.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int]
_lib.scl_gram_compute.restype = c_int

def scl_gram_compute(matrix, output, n_rows):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output: scl_real_t *
        n_rows: int
    
    Returns:
        int
    """
    return _lib.scl_gram_compute(matrix, output, n_rows)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_gram_compute",
]