"""
Auto-generated Python bindings for grn

Source: scl/binding/c_api/grn.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_grn_method_t:
    """C enum: scl_grn_method_t"""
    SCL_GRN_METHOD_CORRELATION = 0
    SCL_GRN_METHOD_PARTIAL_CORRELATION = 1
    SCL_GRN_METHOD_MUTUAL_INFORMATION = 2
    SCL_GRN_METHOD_GENIE3 = 3
    SCL_GRN_METHOD_COMBINED = 4

class scl_grn_method_t:
    """C enum: scl_grn_method_t"""
    SCL_GRN_METHOD_CORRELATION = 0
    SCL_GRN_METHOD_PARTIAL_CORRELATION = 1
    SCL_GRN_METHOD_MUTUAL_INFORMATION = 2
    SCL_GRN_METHOD_GENIE3 = 3
    SCL_GRN_METHOD_COMBINED = 4

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_grn_method_t = c_void_p  # typedef enum scl_grn_method_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_grn_correlation_network(struct scl_sparse_matrix * expression, long n_cells, long n_genes, double threshold, scl_real_t * correlation_matrix, int use_spearman)
_lib.scl_grn_correlation_network.argtypes = [POINTER(c_void_p), c_long, c_long, c_double, POINTER(c_double), c_int]
_lib.scl_grn_correlation_network.restype = c_int

def scl_grn_correlation_network(expression, n_cells, n_genes, threshold, correlation_matrix, use_spearman):
    """
    Args:
        expression: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        threshold: double
        correlation_matrix: scl_real_t *
        use_spearman: int
    
    Returns:
        int
    """
    return _lib.scl_grn_correlation_network(expression, n_cells, n_genes, threshold, correlation_matrix, use_spearman)


# C: int scl_grn_correlation_network_sparse(struct scl_sparse_matrix * expression, long n_cells, long n_genes, double threshold, scl_index_t * edge_row, scl_index_t * edge_col, scl_real_t * edge_weight, long max_edges, scl_index_t * out_n_edges, int use_spearman)
_lib.scl_grn_correlation_network_sparse.argtypes = [POINTER(c_void_p), c_long, c_long, c_double, POINTER(c_int64), POINTER(c_int64), POINTER(c_double), c_long, POINTER(c_int64), c_int]
_lib.scl_grn_correlation_network_sparse.restype = c_int

def scl_grn_correlation_network_sparse(expression, n_cells, n_genes, threshold, edge_row, edge_col, edge_weight, max_edges, out_n_edges, use_spearman):
    """
    Args:
        expression: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        threshold: double
        edge_row: scl_index_t *
        edge_col: scl_index_t *
        edge_weight: scl_real_t *
        max_edges: long
        out_n_edges: scl_index_t *
        use_spearman: int
    
    Returns:
        int
    """
    return _lib.scl_grn_correlation_network_sparse(expression, n_cells, n_genes, threshold, edge_row, edge_col, edge_weight, max_edges, out_n_edges, use_spearman)


# C: int scl_grn_tf_target_score(struct scl_sparse_matrix * expression, const scl_index_t * tf_genes, long n_tfs, const scl_index_t * target_genes, long n_targets, long n_cells, long n_genes, scl_real_t * scores)
_lib.scl_grn_tf_target_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_int64), c_long, c_long, c_long, POINTER(c_double)]
_lib.scl_grn_tf_target_score.restype = c_int

def scl_grn_tf_target_score(expression, tf_genes, n_tfs, target_genes, n_targets, n_cells, n_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        tf_genes: const scl_index_t *
        n_tfs: long
        target_genes: const scl_index_t *
        n_targets: long
        n_cells: long
        n_genes: long
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_grn_tf_target_score(expression, tf_genes, n_tfs, target_genes, n_targets, n_cells, n_genes, scores)


# C: int scl_grn_infer(struct scl_sparse_matrix * expression, const scl_index_t * tf_genes, long n_tfs, long n_cells, long n_genes, scl_real_t * grn_matrix, scl_grn_method_t method, double threshold)
_lib.scl_grn_infer.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, c_long, c_long, POINTER(c_double), c_void_p, c_double]
_lib.scl_grn_infer.restype = c_int

def scl_grn_infer(expression, tf_genes, n_tfs, n_cells, n_genes, grn_matrix, method, threshold):
    """
    Args:
        expression: struct scl_sparse_matrix *
        tf_genes: const scl_index_t *
        n_tfs: long
        n_cells: long
        n_genes: long
        grn_matrix: scl_real_t *
        method: scl_grn_method_t
        threshold: double
    
    Returns:
        int
    """
    return _lib.scl_grn_infer(expression, tf_genes, n_tfs, n_cells, n_genes, grn_matrix, method, threshold)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_grn_correlation_network",
    "scl_grn_correlation_network_sparse",
    "scl_grn_infer",
    "scl_grn_method_t",
    "scl_grn_method_t",
    "scl_grn_method_t",
    "scl_grn_tf_target_score",
]