"""
Auto-generated Python bindings for group

Source: scl/binding/c_api/group.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_group_stats(struct scl_sparse_matrix * matrix, const int32_t * group_ids, int n_groups, const scl_size_t * group_sizes, scl_real_t * out_means, scl_real_t * out_vars, int ddof, int include_zeros)
_lib.scl_group_stats.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, POINTER(c_int), POINTER(c_double), POINTER(c_double), c_int, c_int]
_lib.scl_group_stats.restype = c_int

def scl_group_stats(matrix, group_ids, n_groups, group_sizes, out_means, out_vars, ddof, include_zeros):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        n_groups: int
        group_sizes: const scl_size_t *
        out_means: scl_real_t *
        out_vars: scl_real_t *
        ddof: int
        include_zeros: int
    
    Returns:
        int
    """
    return _lib.scl_group_stats(matrix, group_ids, n_groups, group_sizes, out_means, out_vars, ddof, include_zeros)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_group_stats",
]