"""
Auto-generated Python bindings for hotspot

Source: scl/binding/c_api/hotspot.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_hotspot_local_morans_i(struct scl_sparse_matrix * spatial_weights, const scl_real_t * values, long n, scl_real_t * local_i, scl_real_t * z_scores, scl_real_t * p_values, long n_permutations, unsigned long seed)
_lib.scl_hotspot_local_morans_i.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_long, c_ulong]
_lib.scl_hotspot_local_morans_i.restype = c_int

def scl_hotspot_local_morans_i(spatial_weights, values, n, local_i, z_scores, p_values, n_permutations, seed):
    """
    Args:
        spatial_weights: struct scl_sparse_matrix *
        values: const scl_real_t *
        n: long
        local_i: scl_real_t *
        z_scores: scl_real_t *
        p_values: scl_real_t *
        n_permutations: long
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_hotspot_local_morans_i(spatial_weights, values, n, local_i, z_scores, p_values, n_permutations, seed)


# C: int scl_hotspot_getis_ord_g_star(struct scl_sparse_matrix * spatial_weights, const scl_real_t * values, long n, scl_real_t * g_star, scl_real_t * z_scores, scl_real_t * p_values, int include_self)
_lib.scl_hotspot_getis_ord_g_star.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int]
_lib.scl_hotspot_getis_ord_g_star.restype = c_int

def scl_hotspot_getis_ord_g_star(spatial_weights, values, n, g_star, z_scores, p_values, include_self):
    """
    Args:
        spatial_weights: struct scl_sparse_matrix *
        values: const scl_real_t *
        n: long
        g_star: scl_real_t *
        z_scores: scl_real_t *
        p_values: scl_real_t *
        include_self: int
    
    Returns:
        int
    """
    return _lib.scl_hotspot_getis_ord_g_star(spatial_weights, values, n, g_star, z_scores, p_values, include_self)


# C: int scl_hotspot_local_gearys_c(struct scl_sparse_matrix * spatial_weights, const scl_real_t * values, long n, scl_real_t * local_c, scl_real_t * z_scores, scl_real_t * p_values, long n_permutations, unsigned long seed)
_lib.scl_hotspot_local_gearys_c.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), POINTER(c_double), POINTER(c_double), c_long, c_ulong]
_lib.scl_hotspot_local_gearys_c.restype = c_int

def scl_hotspot_local_gearys_c(spatial_weights, values, n, local_c, z_scores, p_values, n_permutations, seed):
    """
    Args:
        spatial_weights: struct scl_sparse_matrix *
        values: const scl_real_t *
        n: long
        local_c: scl_real_t *
        z_scores: scl_real_t *
        p_values: scl_real_t *
        n_permutations: long
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_hotspot_local_gearys_c(spatial_weights, values, n, local_c, z_scores, p_values, n_permutations, seed)


# C: int scl_hotspot_global_morans_i(struct scl_sparse_matrix * spatial_weights, const scl_real_t * values, long n, scl_real_t * moran_i, scl_real_t * z_score, scl_real_t * p_value)
_lib.scl_hotspot_global_morans_i.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), POINTER(c_double), POINTER(c_double)]
_lib.scl_hotspot_global_morans_i.restype = c_int

def scl_hotspot_global_morans_i(spatial_weights, values, n, moran_i, z_score, p_value):
    """
    Args:
        spatial_weights: struct scl_sparse_matrix *
        values: const scl_real_t *
        n: long
        moran_i: scl_real_t *
        z_score: scl_real_t *
        p_value: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_hotspot_global_morans_i(spatial_weights, values, n, moran_i, z_score, p_value)


# C: int scl_hotspot_global_gearys_c(struct scl_sparse_matrix * spatial_weights, const scl_real_t * values, long n, scl_real_t * geary_c, scl_real_t * z_score, scl_real_t * p_value)
_lib.scl_hotspot_global_gearys_c.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), POINTER(c_double), POINTER(c_double)]
_lib.scl_hotspot_global_gearys_c.restype = c_int

def scl_hotspot_global_gearys_c(spatial_weights, values, n, geary_c, z_score, p_value):
    """
    Args:
        spatial_weights: struct scl_sparse_matrix *
        values: const scl_real_t *
        n: long
        geary_c: scl_real_t *
        z_score: scl_real_t *
        p_value: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_hotspot_global_gearys_c(spatial_weights, values, n, geary_c, z_score, p_value)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_hotspot_getis_ord_g_star",
    "scl_hotspot_global_gearys_c",
    "scl_hotspot_global_morans_i",
    "scl_hotspot_local_gearys_c",
    "scl_hotspot_local_morans_i",
]