"""
Auto-generated Python bindings for kernel

Source: scl/binding/c_api/kernel.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_kernel_type_t:
    """C enum: scl_kernel_type_t"""
    SCL_KERNEL_GAUSSIAN = 0
    SCL_KERNEL_EPANECHNIKOV = 1
    SCL_KERNEL_COSINE = 2
    SCL_KERNEL_LINEAR = 3
    SCL_KERNEL_POLYNOMIAL = 4
    SCL_KERNEL_LAPLACIAN = 5
    SCL_KERNEL_CAUCHY = 6
    SCL_KERNEL_SIGMOID = 7
    SCL_KERNEL_UNIFORM = 8
    SCL_KERNEL_TRIANGULAR = 9

class scl_kernel_type_t:
    """C enum: scl_kernel_type_t"""
    SCL_KERNEL_GAUSSIAN = 0
    SCL_KERNEL_EPANECHNIKOV = 1
    SCL_KERNEL_COSINE = 2
    SCL_KERNEL_LINEAR = 3
    SCL_KERNEL_POLYNOMIAL = 4
    SCL_KERNEL_LAPLACIAN = 5
    SCL_KERNEL_CAUCHY = 6
    SCL_KERNEL_SIGMOID = 7
    SCL_KERNEL_UNIFORM = 8
    SCL_KERNEL_TRIANGULAR = 9

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_kernel_type_t = c_void_p  # typedef enum scl_kernel_type_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_kernel_kde_from_distances(struct scl_sparse_matrix * distances, scl_real_t * density, int n_points, double bandwidth, scl_kernel_type_t kernel_type)
_lib.scl_kernel_kde_from_distances.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, c_double, c_void_p]
_lib.scl_kernel_kde_from_distances.restype = c_int

def scl_kernel_kde_from_distances(distances, density, n_points, bandwidth, kernel_type):
    """
    Args:
        distances: struct scl_sparse_matrix *
        density: scl_real_t *
        n_points: int
        bandwidth: double
        kernel_type: scl_kernel_type_t
    
    Returns:
        int
    """
    return _lib.scl_kernel_kde_from_distances(distances, density, n_points, bandwidth, kernel_type)


# C: int scl_kernel_local_bandwidth(struct scl_sparse_matrix * distances, scl_real_t * bandwidths, int n_points, long k)
_lib.scl_kernel_local_bandwidth.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, c_long]
_lib.scl_kernel_local_bandwidth.restype = c_int

def scl_kernel_local_bandwidth(distances, bandwidths, n_points, k):
    """
    Args:
        distances: struct scl_sparse_matrix *
        bandwidths: scl_real_t *
        n_points: int
        k: long
    
    Returns:
        int
    """
    return _lib.scl_kernel_local_bandwidth(distances, bandwidths, n_points, k)


# C: int scl_kernel_adaptive_kde(struct scl_sparse_matrix * distances, scl_real_t * density, int n_points, const scl_real_t * bandwidths, scl_kernel_type_t kernel_type)
_lib.scl_kernel_adaptive_kde.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, POINTER(c_double), c_void_p]
_lib.scl_kernel_adaptive_kde.restype = c_int

def scl_kernel_adaptive_kde(distances, density, n_points, bandwidths, kernel_type):
    """
    Args:
        distances: struct scl_sparse_matrix *
        density: scl_real_t *
        n_points: int
        bandwidths: const scl_real_t *
        kernel_type: scl_kernel_type_t
    
    Returns:
        int
    """
    return _lib.scl_kernel_adaptive_kde(distances, density, n_points, bandwidths, kernel_type)


# C: int scl_kernel_compute_matrix(struct scl_sparse_matrix * distances, scl_real_t * kernel_values, double bandwidth, scl_kernel_type_t kernel_type)
_lib.scl_kernel_compute_matrix.argtypes = [POINTER(c_void_p), POINTER(c_double), c_double, c_void_p]
_lib.scl_kernel_compute_matrix.restype = c_int

def scl_kernel_compute_matrix(distances, kernel_values, bandwidth, kernel_type):
    """
    Args:
        distances: struct scl_sparse_matrix *
        kernel_values: scl_real_t *
        bandwidth: double
        kernel_type: scl_kernel_type_t
    
    Returns:
        int
    """
    return _lib.scl_kernel_compute_matrix(distances, kernel_values, bandwidth, kernel_type)


# C: int scl_kernel_row_sums(struct scl_sparse_matrix * distances, scl_real_t * sums, int n_points, double bandwidth, scl_kernel_type_t kernel_type)
_lib.scl_kernel_row_sums.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, c_double, c_void_p]
_lib.scl_kernel_row_sums.restype = c_int

def scl_kernel_row_sums(distances, sums, n_points, bandwidth, kernel_type):
    """
    Args:
        distances: struct scl_sparse_matrix *
        sums: scl_real_t *
        n_points: int
        bandwidth: double
        kernel_type: scl_kernel_type_t
    
    Returns:
        int
    """
    return _lib.scl_kernel_row_sums(distances, sums, n_points, bandwidth, kernel_type)


# C: int scl_kernel_nadaraya_watson(struct scl_sparse_matrix * distances, const scl_real_t * y_values, scl_real_t * predictions, int n_points, double bandwidth, scl_kernel_type_t kernel_type)
_lib.scl_kernel_nadaraya_watson.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), c_int, c_double, c_void_p]
_lib.scl_kernel_nadaraya_watson.restype = c_int

def scl_kernel_nadaraya_watson(distances, y_values, predictions, n_points, bandwidth, kernel_type):
    """
    Args:
        distances: struct scl_sparse_matrix *
        y_values: const scl_real_t *
        predictions: scl_real_t *
        n_points: int
        bandwidth: double
        kernel_type: scl_kernel_type_t
    
    Returns:
        int
    """
    return _lib.scl_kernel_nadaraya_watson(distances, y_values, predictions, n_points, bandwidth, kernel_type)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_kernel_adaptive_kde",
    "scl_kernel_compute_matrix",
    "scl_kernel_kde_from_distances",
    "scl_kernel_local_bandwidth",
    "scl_kernel_nadaraya_watson",
    "scl_kernel_row_sums",
    "scl_kernel_type_t",
    "scl_kernel_type_t",
    "scl_kernel_type_t",
]