"""
Auto-generated Python bindings for leiden

Source: scl/binding/c_api/leiden.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_leiden_cluster(struct scl_sparse_matrix * adjacency, scl_index_t * partition, int n_nodes, double resolution, long max_iter, scl_index_t * out_n_communities)
_lib.scl_leiden_cluster.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_double, c_long, POINTER(c_int64)]
_lib.scl_leiden_cluster.restype = c_int

def scl_leiden_cluster(adjacency, partition, n_nodes, resolution, max_iter, out_n_communities):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        partition: scl_index_t *
        n_nodes: int
        resolution: double
        max_iter: long
        out_n_communities: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_leiden_cluster(adjacency, partition, n_nodes, resolution, max_iter, out_n_communities)


# C: int scl_leiden_cluster_multilevel(struct scl_sparse_matrix * adjacency, scl_index_t * partition, int n_nodes, double resolution, long max_iter, scl_index_t * out_n_communities)
_lib.scl_leiden_cluster_multilevel.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_double, c_long, POINTER(c_int64)]
_lib.scl_leiden_cluster_multilevel.restype = c_int

def scl_leiden_cluster_multilevel(adjacency, partition, n_nodes, resolution, max_iter, out_n_communities):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        partition: scl_index_t *
        n_nodes: int
        resolution: double
        max_iter: long
        out_n_communities: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_leiden_cluster_multilevel(adjacency, partition, n_nodes, resolution, max_iter, out_n_communities)


# C: int scl_leiden_compute_modularity(struct scl_sparse_matrix * adjacency, const scl_index_t * partition, int n_nodes, double resolution, scl_real_t * out_modularity)
_lib.scl_leiden_compute_modularity.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_double, POINTER(c_double)]
_lib.scl_leiden_compute_modularity.restype = c_int

def scl_leiden_compute_modularity(adjacency, partition, n_nodes, resolution, out_modularity):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        partition: const scl_index_t *
        n_nodes: int
        resolution: double
        out_modularity: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_leiden_compute_modularity(adjacency, partition, n_nodes, resolution, out_modularity)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_leiden_cluster",
    "scl_leiden_cluster_multilevel",
    "scl_leiden_compute_modularity",
]