"""
Auto-generated Python bindings for lineage

Source: scl/binding/c_api/lineage.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_lineage_coupling(const scl_index_t * clone_ids, const scl_index_t * cell_types, scl_real_t * coupling_matrix, int n_cells, int n_clones, int n_types)
_lib.scl_lineage_coupling.argtypes = [POINTER(c_int64), POINTER(c_int64), POINTER(c_double), c_int, c_int, c_int]
_lib.scl_lineage_coupling.restype = c_int

def scl_lineage_coupling(clone_ids, cell_types, coupling_matrix, n_cells, n_clones, n_types):
    """
    Args:
        clone_ids: const scl_index_t *
        cell_types: const scl_index_t *
        coupling_matrix: scl_real_t *
        n_cells: int
        n_clones: int
        n_types: int
    
    Returns:
        int
    """
    return _lib.scl_lineage_coupling(clone_ids, cell_types, coupling_matrix, n_cells, n_clones, n_types)


# C: int scl_lineage_fate_bias(const scl_index_t * clone_ids, const scl_index_t * cell_types, scl_real_t * bias_scores, int n_cells, int n_types)
_lib.scl_lineage_fate_bias.argtypes = [POINTER(c_int64), POINTER(c_int64), POINTER(c_double), c_int, c_int]
_lib.scl_lineage_fate_bias.restype = c_int

def scl_lineage_fate_bias(clone_ids, cell_types, bias_scores, n_cells, n_types):
    """
    Args:
        clone_ids: const scl_index_t *
        cell_types: const scl_index_t *
        bias_scores: scl_real_t *
        n_cells: int
        n_types: int
    
    Returns:
        int
    """
    return _lib.scl_lineage_fate_bias(clone_ids, cell_types, bias_scores, n_cells, n_types)


# C: int scl_lineage_build_tree(const scl_index_t * clone_ids, const scl_real_t * pseudotime, scl_index_t * parent, int n_cells, int n_clones)
_lib.scl_lineage_build_tree.argtypes = [POINTER(c_int64), POINTER(c_double), POINTER(c_int64), c_int, c_int]
_lib.scl_lineage_build_tree.restype = c_int

def scl_lineage_build_tree(clone_ids, pseudotime, parent, n_cells, n_clones):
    """
    Args:
        clone_ids: const scl_index_t *
        pseudotime: const scl_real_t *
        parent: scl_index_t *
        n_cells: int
        n_clones: int
    
    Returns:
        int
    """
    return _lib.scl_lineage_build_tree(clone_ids, pseudotime, parent, n_cells, n_clones)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_lineage_build_tree",
    "scl_lineage_coupling",
    "scl_lineage_fate_bias",
]