"""
Auto-generated Python bindings for log1p

Source: scl/binding/c_api/log1p.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_log1p_inplace(scl_sparse_t * matrix)
_lib.scl_log1p_inplace.argtypes = [POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_log1p_inplace.restype = c_int

def scl_log1p_inplace(matrix):
    """
    Args:
        matrix: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_log1p_inplace(matrix)


# C: int scl_log2p1_inplace(scl_sparse_t * matrix)
_lib.scl_log2p1_inplace.argtypes = [POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_log2p1_inplace.restype = c_int

def scl_log2p1_inplace(matrix):
    """
    Args:
        matrix: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_log2p1_inplace(matrix)


# C: int scl_expm1_inplace(scl_sparse_t * matrix)
_lib.scl_expm1_inplace.argtypes = [POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_expm1_inplace.restype = c_int

def scl_expm1_inplace(matrix):
    """
    Args:
        matrix: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_expm1_inplace(matrix)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_expm1_inplace",
    "scl_log1p_inplace",
    "scl_log2p1_inplace",
]