"""
Auto-generated Python bindings for louvain

Source: scl/binding/c_api/louvain.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_louvain_clustering(struct scl_sparse_matrix * adjacency, scl_index_t * labels, int n_nodes, double resolution, long max_iter)
_lib.scl_louvain_clustering.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_double, c_long]
_lib.scl_louvain_clustering.restype = c_int

def scl_louvain_clustering(adjacency, labels, n_nodes, resolution, max_iter):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        labels: scl_index_t *
        n_nodes: int
        resolution: double
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_louvain_clustering(adjacency, labels, n_nodes, resolution, max_iter)


# C: int scl_louvain_compute_modularity(struct scl_sparse_matrix * adjacency, const scl_index_t * labels, int n_nodes, double resolution, scl_real_t * modularity)
_lib.scl_louvain_compute_modularity.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_double, POINTER(c_double)]
_lib.scl_louvain_compute_modularity.restype = c_int

def scl_louvain_compute_modularity(adjacency, labels, n_nodes, resolution, modularity):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        labels: const scl_index_t *
        n_nodes: int
        resolution: double
        modularity: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_louvain_compute_modularity(adjacency, labels, n_nodes, resolution, modularity)


# C: int scl_louvain_community_sizes(const scl_index_t * labels, int n_nodes, scl_index_t * sizes, int sizes_size, scl_index_t * n_communities)
_lib.scl_louvain_community_sizes.argtypes = [POINTER(c_int64), c_int, POINTER(c_int64), c_int, POINTER(c_int64)]
_lib.scl_louvain_community_sizes.restype = c_int

def scl_louvain_community_sizes(labels, n_nodes, sizes, sizes_size, n_communities):
    """
    Args:
        labels: const scl_index_t *
        n_nodes: int
        sizes: scl_index_t *
        sizes_size: int
        n_communities: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_louvain_community_sizes(labels, n_nodes, sizes, sizes_size, n_communities)


# C: int scl_louvain_get_community_members(const scl_index_t * labels, int n_nodes, long community, scl_index_t * members, int members_size, scl_index_t * n_members)
_lib.scl_louvain_get_community_members.argtypes = [POINTER(c_int64), c_int, c_long, POINTER(c_int64), c_int, POINTER(c_int64)]
_lib.scl_louvain_get_community_members.restype = c_int

def scl_louvain_get_community_members(labels, n_nodes, community, members, members_size, n_members):
    """
    Args:
        labels: const scl_index_t *
        n_nodes: int
        community: long
        members: scl_index_t *
        members_size: int
        n_members: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_louvain_get_community_members(labels, n_nodes, community, members, members_size, n_members)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_louvain_clustering",
    "scl_louvain_community_sizes",
    "scl_louvain_compute_modularity",
    "scl_louvain_get_community_members",
]