"""
Auto-generated Python bindings for markers

Source: scl/binding/c_api/markers.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_markers_group_mean_expression(struct scl_sparse_matrix * expression, const scl_index_t * group_labels, int n_cells, long n_groups, long n_genes, scl_real_t * mean_expr)
_lib.scl_markers_group_mean_expression.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_long, c_long, POINTER(c_double)]
_lib.scl_markers_group_mean_expression.restype = c_int

def scl_markers_group_mean_expression(expression, group_labels, n_cells, n_groups, n_genes, mean_expr):
    """
    Args:
        expression: struct scl_sparse_matrix *
        group_labels: const scl_index_t *
        n_cells: int
        n_groups: long
        n_genes: long
        mean_expr: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_markers_group_mean_expression(expression, group_labels, n_cells, n_groups, n_genes, mean_expr)


# C: int scl_markers_percent_expressed(struct scl_sparse_matrix * expression, const scl_index_t * group_labels, int n_cells, long n_groups, long n_genes, scl_real_t * pct_expr, double threshold)
_lib.scl_markers_percent_expressed.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_long, c_long, POINTER(c_double), c_double]
_lib.scl_markers_percent_expressed.restype = c_int

def scl_markers_percent_expressed(expression, group_labels, n_cells, n_groups, n_genes, pct_expr, threshold):
    """
    Args:
        expression: struct scl_sparse_matrix *
        group_labels: const scl_index_t *
        n_cells: int
        n_groups: long
        n_genes: long
        pct_expr: scl_real_t *
        threshold: double
    
    Returns:
        int
    """
    return _lib.scl_markers_percent_expressed(expression, group_labels, n_cells, n_groups, n_genes, pct_expr, threshold)


# C: int scl_markers_find_markers(struct scl_sparse_matrix * expression, const scl_index_t * group_labels, int n_cells, long n_groups, long n_genes, long target_group, scl_index_t * marker_genes, scl_real_t * marker_scores, scl_size_t * n_markers, double min_fold_change, double min_pct, long n_top)
_lib.scl_markers_find_markers.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_long, c_long, c_long, POINTER(c_int64), POINTER(c_double), POINTER(c_int), c_double, c_double, c_long]
_lib.scl_markers_find_markers.restype = c_int

def scl_markers_find_markers(expression, group_labels, n_cells, n_groups, n_genes, target_group, marker_genes, marker_scores, n_markers, min_fold_change, min_pct, n_top):
    """
    Args:
        expression: struct scl_sparse_matrix *
        group_labels: const scl_index_t *
        n_cells: int
        n_groups: long
        n_genes: long
        target_group: long
        marker_genes: scl_index_t *
        marker_scores: scl_real_t *
        n_markers: scl_size_t *
        min_fold_change: double
        min_pct: double
        n_top: long
    
    Returns:
        int
    """
    return _lib.scl_markers_find_markers(expression, group_labels, n_cells, n_groups, n_genes, target_group, marker_genes, marker_scores, n_markers, min_fold_change, min_pct, n_top)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_markers_find_markers",
    "scl_markers_group_mean_expression",
    "scl_markers_percent_expressed",
]