"""
Auto-generated Python bindings for merge

Source: scl/binding/c_api/merge.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_merge_vstack(struct scl_sparse_matrix * matrix1, struct scl_sparse_matrix * matrix2, scl_sparse_t * result)
_lib.scl_merge_vstack.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_merge_vstack.restype = c_int

def scl_merge_vstack(matrix1, matrix2, result):
    """
    Args:
        matrix1: struct scl_sparse_matrix *
        matrix2: struct scl_sparse_matrix *
        result: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_merge_vstack(matrix1, matrix2, result)


# C: int scl_merge_hstack(struct scl_sparse_matrix * matrix1, struct scl_sparse_matrix * matrix2, scl_sparse_t * result)
_lib.scl_merge_hstack.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_merge_hstack.restype = c_int

def scl_merge_hstack(matrix1, matrix2, result):
    """
    Args:
        matrix1: struct scl_sparse_matrix *
        matrix2: struct scl_sparse_matrix *
        result: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_merge_hstack(matrix1, matrix2, result)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_merge_hstack",
    "scl_merge_vstack",
]