"""
Auto-generated Python bindings for metrics

Source: scl/binding/c_api/metrics.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_metrics_silhouette_score(struct scl_sparse_matrix * distances, const scl_index_t * labels, int n_cells, scl_real_t * score)
_lib.scl_metrics_silhouette_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_silhouette_score.restype = c_int

def scl_metrics_silhouette_score(distances, labels, n_cells, score):
    """
    Args:
        distances: struct scl_sparse_matrix *
        labels: const scl_index_t *
        n_cells: int
        score: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_silhouette_score(distances, labels, n_cells, score)


# C: int scl_metrics_silhouette_samples(struct scl_sparse_matrix * distances, const scl_index_t * labels, int n_cells, scl_real_t * scores)
_lib.scl_metrics_silhouette_samples.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_silhouette_samples.restype = c_int

def scl_metrics_silhouette_samples(distances, labels, n_cells, scores):
    """
    Args:
        distances: struct scl_sparse_matrix *
        labels: const scl_index_t *
        n_cells: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_silhouette_samples(distances, labels, n_cells, scores)


# C: int scl_metrics_adjusted_rand_index(const scl_index_t * labels1, const scl_index_t * labels2, int n_cells, scl_real_t * ari)
_lib.scl_metrics_adjusted_rand_index.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_adjusted_rand_index.restype = c_int

def scl_metrics_adjusted_rand_index(labels1, labels2, n_cells, ari):
    """
    Args:
        labels1: const scl_index_t *
        labels2: const scl_index_t *
        n_cells: int
        ari: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_adjusted_rand_index(labels1, labels2, n_cells, ari)


# C: int scl_metrics_normalized_mutual_information(const scl_index_t * labels1, const scl_index_t * labels2, int n_cells, scl_real_t * nmi)
_lib.scl_metrics_normalized_mutual_information.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_normalized_mutual_information.restype = c_int

def scl_metrics_normalized_mutual_information(labels1, labels2, n_cells, nmi):
    """
    Args:
        labels1: const scl_index_t *
        labels2: const scl_index_t *
        n_cells: int
        nmi: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_normalized_mutual_information(labels1, labels2, n_cells, nmi)


# C: int scl_metrics_homogeneity_score(const scl_index_t * labels_true, const scl_index_t * labels_pred, int n_cells, scl_real_t * homogeneity)
_lib.scl_metrics_homogeneity_score.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_homogeneity_score.restype = c_int

def scl_metrics_homogeneity_score(labels_true, labels_pred, n_cells, homogeneity):
    """
    Args:
        labels_true: const scl_index_t *
        labels_pred: const scl_index_t *
        n_cells: int
        homogeneity: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_homogeneity_score(labels_true, labels_pred, n_cells, homogeneity)


# C: int scl_metrics_completeness_score(const scl_index_t * labels_true, const scl_index_t * labels_pred, int n_cells, scl_real_t * completeness)
_lib.scl_metrics_completeness_score.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_completeness_score.restype = c_int

def scl_metrics_completeness_score(labels_true, labels_pred, n_cells, completeness):
    """
    Args:
        labels_true: const scl_index_t *
        labels_pred: const scl_index_t *
        n_cells: int
        completeness: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_completeness_score(labels_true, labels_pred, n_cells, completeness)


# C: int scl_metrics_v_measure(const scl_index_t * labels_true, const scl_index_t * labels_pred, int n_cells, scl_real_t * v_measure)
_lib.scl_metrics_v_measure.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_metrics_v_measure.restype = c_int

def scl_metrics_v_measure(labels_true, labels_pred, n_cells, v_measure):
    """
    Args:
        labels_true: const scl_index_t *
        labels_pred: const scl_index_t *
        n_cells: int
        v_measure: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_metrics_v_measure(labels_true, labels_pred, n_cells, v_measure)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_metrics_adjusted_rand_index",
    "scl_metrics_completeness_score",
    "scl_metrics_homogeneity_score",
    "scl_metrics_normalized_mutual_information",
    "scl_metrics_silhouette_samples",
    "scl_metrics_silhouette_score",
    "scl_metrics_v_measure",
]