"""
Auto-generated Python bindings for neighbors

Source: scl/binding/c_api/neighbors.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_neighbors_compute_norms(struct scl_sparse_matrix * matrix, scl_real_t * norms_sq)
_lib.scl_neighbors_compute_norms.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_neighbors_compute_norms.restype = c_int

def scl_neighbors_compute_norms(matrix, norms_sq):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        norms_sq: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_neighbors_compute_norms(matrix, norms_sq)


# C: int scl_knn(struct scl_sparse_matrix * matrix, const scl_real_t * norms_sq, int n_samples, int k, scl_index_t * out_indices, scl_real_t * out_distances)
_lib.scl_knn.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, c_int, POINTER(c_int64), POINTER(c_double)]
_lib.scl_knn.restype = c_int

def scl_knn(matrix, norms_sq, n_samples, k, out_indices, out_distances):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        norms_sq: const scl_real_t *
        n_samples: int
        k: int
        out_indices: scl_index_t *
        out_distances: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_knn(matrix, norms_sq, n_samples, k, out_indices, out_distances)


# C: int scl_knn_simple(struct scl_sparse_matrix * matrix, int n_samples, int k, scl_index_t * out_indices, scl_real_t * out_distances)
_lib.scl_knn_simple.argtypes = [POINTER(c_void_p), c_int, c_int, POINTER(c_int64), POINTER(c_double)]
_lib.scl_knn_simple.restype = c_int

def scl_knn_simple(matrix, n_samples, k, out_indices, out_distances):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        n_samples: int
        k: int
        out_indices: scl_index_t *
        out_distances: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_knn_simple(matrix, n_samples, k, out_indices, out_distances)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_knn",
    "scl_knn_simple",
    "scl_neighbors_compute_norms",
]