"""
Auto-generated Python bindings for niche

Source: scl/binding/c_api/niche.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_niche_neighborhood_composition(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * composition_output)
_lib.scl_niche_neighborhood_composition.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double)]
_lib.scl_niche_neighborhood_composition.restype = c_int

def scl_niche_neighborhood_composition(spatial_neighbors, cell_type_labels, n_cell_types, composition_output):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        composition_output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_neighborhood_composition(spatial_neighbors, cell_type_labels, n_cell_types, composition_output)


# C: int scl_niche_neighborhood_enrichment(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * enrichment_scores, scl_real_t * p_values, long n_permutations)
_lib.scl_niche_neighborhood_enrichment.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double), POINTER(c_double), c_long]
_lib.scl_niche_neighborhood_enrichment.restype = c_int

def scl_niche_neighborhood_enrichment(spatial_neighbors, cell_type_labels, n_cell_types, enrichment_scores, p_values, n_permutations):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        enrichment_scores: scl_real_t *
        p_values: scl_real_t *
        n_permutations: long
    
    Returns:
        int
    """
    return _lib.scl_niche_neighborhood_enrichment(spatial_neighbors, cell_type_labels, n_cell_types, enrichment_scores, p_values, n_permutations)


# C: int scl_niche_cell_cell_contact(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * contact_matrix)
_lib.scl_niche_cell_cell_contact.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double)]
_lib.scl_niche_cell_cell_contact.restype = c_int

def scl_niche_cell_cell_contact(spatial_neighbors, cell_type_labels, n_cell_types, contact_matrix):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        contact_matrix: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_cell_cell_contact(spatial_neighbors, cell_type_labels, n_cell_types, contact_matrix)


# C: int scl_niche_colocalization_score(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, long type_a, long type_b, scl_real_t * colocalization, scl_real_t * p_value, long n_permutations)
_lib.scl_niche_colocalization_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, c_long, c_long, POINTER(c_double), POINTER(c_double), c_long]
_lib.scl_niche_colocalization_score.restype = c_int

def scl_niche_colocalization_score(spatial_neighbors, cell_type_labels, n_cell_types, type_a, type_b, colocalization, p_value, n_permutations):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        type_a: long
        type_b: long
        colocalization: scl_real_t *
        p_value: scl_real_t *
        n_permutations: long
    
    Returns:
        int
    """
    return _lib.scl_niche_colocalization_score(spatial_neighbors, cell_type_labels, n_cell_types, type_a, type_b, colocalization, p_value, n_permutations)


# C: int scl_niche_colocalization_matrix(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * coloc_matrix)
_lib.scl_niche_colocalization_matrix.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double)]
_lib.scl_niche_colocalization_matrix.restype = c_int

def scl_niche_colocalization_matrix(spatial_neighbors, cell_type_labels, n_cell_types, coloc_matrix):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        coloc_matrix: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_colocalization_matrix(spatial_neighbors, cell_type_labels, n_cell_types, coloc_matrix)


# C: int scl_niche_similarity(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, const scl_index_t * query_cells, int n_query, scl_real_t * similarity_output)
_lib.scl_niche_similarity.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_niche_similarity.restype = c_int

def scl_niche_similarity(spatial_neighbors, cell_type_labels, n_cell_types, query_cells, n_query, similarity_output):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        query_cells: const scl_index_t *
        n_query: int
        similarity_output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_similarity(spatial_neighbors, cell_type_labels, n_cell_types, query_cells, n_query, similarity_output)


# C: int scl_niche_diversity(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * diversity_output)
_lib.scl_niche_diversity.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double)]
_lib.scl_niche_diversity.restype = c_int

def scl_niche_diversity(spatial_neighbors, cell_type_labels, n_cell_types, diversity_output):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        diversity_output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_diversity(spatial_neighbors, cell_type_labels, n_cell_types, diversity_output)


# C: int scl_niche_boundary_score(struct scl_sparse_matrix * spatial_neighbors, const scl_index_t * cell_type_labels, long n_cell_types, scl_real_t * boundary_scores)
_lib.scl_niche_boundary_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, POINTER(c_double)]
_lib.scl_niche_boundary_score.restype = c_int

def scl_niche_boundary_score(spatial_neighbors, cell_type_labels, n_cell_types, boundary_scores):
    """
    Args:
        spatial_neighbors: struct scl_sparse_matrix *
        cell_type_labels: const scl_index_t *
        n_cell_types: long
        boundary_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_niche_boundary_score(spatial_neighbors, cell_type_labels, n_cell_types, boundary_scores)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_niche_boundary_score",
    "scl_niche_cell_cell_contact",
    "scl_niche_colocalization_matrix",
    "scl_niche_colocalization_score",
    "scl_niche_diversity",
    "scl_niche_neighborhood_composition",
    "scl_niche_neighborhood_enrichment",
    "scl_niche_similarity",
]