"""
Auto-generated Python bindings for outlier

Source: scl/binding/c_api/outlier.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_outlier_isolation_score(struct scl_sparse_matrix * data, scl_real_t * scores)
_lib.scl_outlier_isolation_score.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_outlier_isolation_score.restype = c_int

def scl_outlier_isolation_score(data, scores):
    """
    Args:
        data: struct scl_sparse_matrix *
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_outlier_isolation_score(data, scores)


# C: int scl_outlier_ambient_detection(struct scl_sparse_matrix * expression, scl_real_t * ambient_scores)
_lib.scl_outlier_ambient_detection.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_outlier_ambient_detection.restype = c_int

def scl_outlier_ambient_detection(expression, ambient_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        ambient_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_outlier_ambient_detection(expression, ambient_scores)


# C: int scl_outlier_empty_drops(struct scl_sparse_matrix * raw_counts, unsigned char * is_empty, double fdr_threshold)
_lib.scl_outlier_empty_drops.argtypes = [POINTER(c_void_p), POINTER(c_ubyte), c_double]
_lib.scl_outlier_empty_drops.restype = c_int

def scl_outlier_empty_drops(raw_counts, is_empty, fdr_threshold):
    """
    Args:
        raw_counts: struct scl_sparse_matrix *
        is_empty: unsigned char *
        fdr_threshold: double
    
    Returns:
        int
    """
    return _lib.scl_outlier_empty_drops(raw_counts, is_empty, fdr_threshold)


# C: int scl_outlier_outlier_genes(struct scl_sparse_matrix * expression, scl_index_t * outlier_gene_indices, int max_outliers, scl_size_t * n_outliers, double threshold)
_lib.scl_outlier_outlier_genes.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int), c_double]
_lib.scl_outlier_outlier_genes.restype = c_int

def scl_outlier_outlier_genes(expression, outlier_gene_indices, max_outliers, n_outliers, threshold):
    """
    Args:
        expression: struct scl_sparse_matrix *
        outlier_gene_indices: scl_index_t *
        max_outliers: int
        n_outliers: scl_size_t *
        threshold: double
    
    Returns:
        int
    """
    return _lib.scl_outlier_outlier_genes(expression, outlier_gene_indices, max_outliers, n_outliers, threshold)


# C: int scl_outlier_doublet_score(struct scl_sparse_matrix * expression, struct scl_sparse_matrix * neighbors, scl_real_t * scores)
_lib.scl_outlier_doublet_score.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_double)]
_lib.scl_outlier_doublet_score.restype = c_int

def scl_outlier_doublet_score(expression, neighbors, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        neighbors: struct scl_sparse_matrix *
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_outlier_doublet_score(expression, neighbors, scores)


# C: int scl_outlier_mitochondrial_outliers(struct scl_sparse_matrix * expression, const scl_index_t * mito_genes, int n_mito_genes, scl_real_t * mito_fraction, unsigned char * is_outlier, double threshold)
_lib.scl_outlier_mitochondrial_outliers.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), POINTER(c_ubyte), c_double]
_lib.scl_outlier_mitochondrial_outliers.restype = c_int

def scl_outlier_mitochondrial_outliers(expression, mito_genes, n_mito_genes, mito_fraction, is_outlier, threshold):
    """
    Args:
        expression: struct scl_sparse_matrix *
        mito_genes: const scl_index_t *
        n_mito_genes: int
        mito_fraction: scl_real_t *
        is_outlier: unsigned char *
        threshold: double
    
    Returns:
        int
    """
    return _lib.scl_outlier_mitochondrial_outliers(expression, mito_genes, n_mito_genes, mito_fraction, is_outlier, threshold)


# C: int scl_outlier_qc_filter(struct scl_sparse_matrix * expression, double min_genes, double max_genes, double min_counts, double max_counts, double max_mito_fraction, const scl_index_t * mito_genes, int n_mito_genes, unsigned char * pass_qc)
_lib.scl_outlier_qc_filter.argtypes = [POINTER(c_void_p), c_double, c_double, c_double, c_double, c_double, POINTER(c_int64), c_int, POINTER(c_ubyte)]
_lib.scl_outlier_qc_filter.restype = c_int

def scl_outlier_qc_filter(expression, min_genes, max_genes, min_counts, max_counts, max_mito_fraction, mito_genes, n_mito_genes, pass_qc):
    """
    Args:
        expression: struct scl_sparse_matrix *
        min_genes: double
        max_genes: double
        min_counts: double
        max_counts: double
        max_mito_fraction: double
        mito_genes: const scl_index_t *
        n_mito_genes: int
        pass_qc: unsigned char *
    
    Returns:
        int
    """
    return _lib.scl_outlier_qc_filter(expression, min_genes, max_genes, min_counts, max_counts, max_mito_fraction, mito_genes, n_mito_genes, pass_qc)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_outlier_ambient_detection",
    "scl_outlier_doublet_score",
    "scl_outlier_empty_drops",
    "scl_outlier_isolation_score",
    "scl_outlier_mitochondrial_outliers",
    "scl_outlier_outlier_genes",
    "scl_outlier_qc_filter",
]