"""
Auto-generated Python bindings for projection

Source: scl/binding/c_api/projection.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_projection_type_t:
    """C enum: scl_projection_type_t"""
    SCL_PROJECTION_GAUSSIAN = 0
    SCL_PROJECTION_ACHLIOPTAS = 1
    SCL_PROJECTION_SPARSE = 2
    SCL_PROJECTION_COUNTSKETCH = 3
    SCL_PROJECTION_FEATURE_HASH = 4

class scl_projection_type_t:
    """C enum: scl_projection_type_t"""
    SCL_PROJECTION_GAUSSIAN = 0
    SCL_PROJECTION_ACHLIOPTAS = 1
    SCL_PROJECTION_SPARSE = 2
    SCL_PROJECTION_COUNTSKETCH = 3
    SCL_PROJECTION_FEATURE_HASH = 4

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_projection_type_t = c_void_p  # typedef enum scl_projection_type_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_projection_project(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, scl_projection_type_t type, unsigned long seed)
_lib.scl_projection_project.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_void_p, c_ulong]
_lib.scl_projection_project.restype = c_int

def scl_projection_project(matrix, output_dim, output, type, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        type: scl_projection_type_t
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_project(matrix, output_dim, output, type, seed)


# C: int scl_projection_project_auto(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, unsigned long seed)
_lib.scl_projection_project_auto.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_ulong]
_lib.scl_projection_project_auto.restype = c_int

def scl_projection_project_auto(matrix, output_dim, output, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_project_auto(matrix, output_dim, output, seed)


# C: int scl_projection_gaussian(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, unsigned long seed)
_lib.scl_projection_gaussian.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_ulong]
_lib.scl_projection_gaussian.restype = c_int

def scl_projection_gaussian(matrix, output_dim, output, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_gaussian(matrix, output_dim, output, seed)


# C: int scl_projection_achlioptas(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, unsigned long seed)
_lib.scl_projection_achlioptas.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_ulong]
_lib.scl_projection_achlioptas.restype = c_int

def scl_projection_achlioptas(matrix, output_dim, output, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_achlioptas(matrix, output_dim, output, seed)


# C: int scl_projection_sparse(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, double density, unsigned long seed)
_lib.scl_projection_sparse.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_double, c_ulong]
_lib.scl_projection_sparse.restype = c_int

def scl_projection_sparse(matrix, output_dim, output, density, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        density: double
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_sparse(matrix, output_dim, output, density, seed)


# C: int scl_projection_countsketch(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, unsigned long seed)
_lib.scl_projection_countsketch.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_ulong]
_lib.scl_projection_countsketch.restype = c_int

def scl_projection_countsketch(matrix, output_dim, output, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_countsketch(matrix, output_dim, output, seed)


# C: int scl_projection_feature_hash(struct scl_sparse_matrix * matrix, int output_dim, scl_real_t * output, int n_hashes, unsigned long seed)
_lib.scl_projection_feature_hash.argtypes = [POINTER(c_void_p), c_int, POINTER(c_double), c_int, c_ulong]
_lib.scl_projection_feature_hash.restype = c_int

def scl_projection_feature_hash(matrix, output_dim, output, n_hashes, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        output_dim: int
        output: scl_real_t *
        n_hashes: int
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_projection_feature_hash(matrix, output_dim, output, n_hashes, seed)


# C: int scl_projection_jl_dimension(int n_samples, double epsilon)
_lib.scl_projection_jl_dimension.argtypes = [c_int, c_double]
_lib.scl_projection_jl_dimension.restype = c_int

def scl_projection_jl_dimension(n_samples, epsilon):
    """
    Args:
        n_samples: int
        epsilon: double
    
    Returns:
        int
    """
    return _lib.scl_projection_jl_dimension(n_samples, epsilon)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_projection_achlioptas",
    "scl_projection_countsketch",
    "scl_projection_feature_hash",
    "scl_projection_gaussian",
    "scl_projection_jl_dimension",
    "scl_projection_project",
    "scl_projection_project_auto",
    "scl_projection_sparse",
    "scl_projection_type_t",
    "scl_projection_type_t",
    "scl_projection_type_t",
]