"""
Auto-generated Python bindings for propagation

Source: scl/binding/c_api/propagation.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_propagation_label_propagation(struct scl_sparse_matrix * adjacency, scl_index_t * labels, long n, long max_iter, unsigned long seed)
_lib.scl_propagation_label_propagation.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_long, c_long, c_ulong]
_lib.scl_propagation_label_propagation.restype = c_int

def scl_propagation_label_propagation(adjacency, labels, n, max_iter, seed):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        labels: scl_index_t *
        n: long
        max_iter: long
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_propagation_label_propagation(adjacency, labels, n, max_iter, seed)


# C: int scl_propagation_label_spreading(struct scl_sparse_matrix * adjacency, scl_real_t * label_probs, const unsigned char * is_labeled, long n, long n_classes, double alpha, long max_iter, double tolerance)
_lib.scl_propagation_label_spreading.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_ubyte), c_long, c_long, c_double, c_long, c_double]
_lib.scl_propagation_label_spreading.restype = c_int

def scl_propagation_label_spreading(adjacency, label_probs, is_labeled, n, n_classes, alpha, max_iter, tolerance):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        label_probs: scl_real_t *
        is_labeled: const unsigned char *
        n: long
        n_classes: long
        alpha: double
        max_iter: long
        tolerance: double
    
    Returns:
        int
    """
    return _lib.scl_propagation_label_spreading(adjacency, label_probs, is_labeled, n, n_classes, alpha, max_iter, tolerance)


# C: int scl_propagation_harmonic_function(struct scl_sparse_matrix * adjacency, scl_real_t * values, const unsigned char * is_known, long n, long max_iter, double tolerance)
_lib.scl_propagation_harmonic_function.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_ubyte), c_long, c_long, c_double]
_lib.scl_propagation_harmonic_function.restype = c_int

def scl_propagation_harmonic_function(adjacency, values, is_known, n, max_iter, tolerance):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        values: scl_real_t *
        is_known: const unsigned char *
        n: long
        max_iter: long
        tolerance: double
    
    Returns:
        int
    """
    return _lib.scl_propagation_harmonic_function(adjacency, values, is_known, n, max_iter, tolerance)


# C: int scl_propagation_confidence(struct scl_sparse_matrix * adjacency, scl_index_t * labels, scl_real_t * confidences, long n, long n_classes, double alpha, long max_iter)
_lib.scl_propagation_confidence.argtypes = [POINTER(c_void_p), POINTER(c_int64), POINTER(c_double), c_long, c_long, c_double, c_long]
_lib.scl_propagation_confidence.restype = c_int

def scl_propagation_confidence(adjacency, labels, confidences, n, n_classes, alpha, max_iter):
    """
    Args:
        adjacency: struct scl_sparse_matrix *
        labels: scl_index_t *
        confidences: scl_real_t *
        n: long
        n_classes: long
        alpha: double
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_propagation_confidence(adjacency, labels, confidences, n, n_classes, alpha, max_iter)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_propagation_confidence",
    "scl_propagation_harmonic_function",
    "scl_propagation_label_propagation",
    "scl_propagation_label_spreading",
]