"""
Auto-generated Python bindings for qc

Source: scl/binding/c_api/qc.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_qc_compute_basic(struct scl_sparse_matrix * matrix, scl_index_t * out_n_genes, scl_real_t * out_total_counts, long primary_dim)
_lib.scl_qc_compute_basic.argtypes = [POINTER(c_void_p), POINTER(c_int64), POINTER(c_double), c_long]
_lib.scl_qc_compute_basic.restype = c_int

def scl_qc_compute_basic(matrix, out_n_genes, out_total_counts, primary_dim):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        out_n_genes: scl_index_t *
        out_total_counts: scl_real_t *
        primary_dim: long
    
    Returns:
        int
    """
    return _lib.scl_qc_compute_basic(matrix, out_n_genes, out_total_counts, primary_dim)


# C: int scl_qc_compute_subset_pct(struct scl_sparse_matrix * matrix, const uint8_t * subset_mask, scl_real_t * out_pcts, long primary_dim)
_lib.scl_qc_compute_subset_pct.argtypes = [POINTER(c_void_p), POINTER(c_uint8), POINTER(c_double), c_long]
_lib.scl_qc_compute_subset_pct.restype = c_int

def scl_qc_compute_subset_pct(matrix, subset_mask, out_pcts, primary_dim):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        subset_mask: const uint8_t *
        out_pcts: scl_real_t *
        primary_dim: long
    
    Returns:
        int
    """
    return _lib.scl_qc_compute_subset_pct(matrix, subset_mask, out_pcts, primary_dim)


# C: int scl_qc_compute_fused(struct scl_sparse_matrix * matrix, const uint8_t * subset_mask, scl_index_t * out_n_genes, scl_real_t * out_total_counts, scl_real_t * out_pcts, long primary_dim)
_lib.scl_qc_compute_fused.argtypes = [POINTER(c_void_p), POINTER(c_uint8), POINTER(c_int64), POINTER(c_double), POINTER(c_double), c_long]
_lib.scl_qc_compute_fused.restype = c_int

def scl_qc_compute_fused(matrix, subset_mask, out_n_genes, out_total_counts, out_pcts, primary_dim):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        subset_mask: const uint8_t *
        out_n_genes: scl_index_t *
        out_total_counts: scl_real_t *
        out_pcts: scl_real_t *
        primary_dim: long
    
    Returns:
        int
    """
    return _lib.scl_qc_compute_fused(matrix, subset_mask, out_n_genes, out_total_counts, out_pcts, primary_dim)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_qc_compute_basic",
    "scl_qc_compute_fused",
    "scl_qc_compute_subset_pct",
]