"""
Auto-generated Python bindings for resample

Source: scl/binding/c_api/resample.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_resample_downsample(struct scl_sparse_matrix * matrix, double target_sum, unsigned long seed)
_lib.scl_resample_downsample.argtypes = [POINTER(c_void_p), c_double, c_ulong]
_lib.scl_resample_downsample.restype = c_int

def scl_resample_downsample(matrix, target_sum, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        target_sum: double
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_resample_downsample(matrix, target_sum, seed)


# C: int scl_resample_downsample_variable(struct scl_sparse_matrix * matrix, const scl_real_t * target_counts, int primary_dim, unsigned long seed)
_lib.scl_resample_downsample_variable.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, c_ulong]
_lib.scl_resample_downsample_variable.restype = c_int

def scl_resample_downsample_variable(matrix, target_counts, primary_dim, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        target_counts: const scl_real_t *
        primary_dim: int
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_resample_downsample_variable(matrix, target_counts, primary_dim, seed)


# C: int scl_resample_binomial(struct scl_sparse_matrix * matrix, double p, unsigned long seed)
_lib.scl_resample_binomial.argtypes = [POINTER(c_void_p), c_double, c_ulong]
_lib.scl_resample_binomial.restype = c_int

def scl_resample_binomial(matrix, p, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        p: double
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_resample_binomial(matrix, p, seed)


# C: int scl_resample_poisson(struct scl_sparse_matrix * matrix, double lambda, unsigned long seed)
_lib.scl_resample_poisson.argtypes = [POINTER(c_void_p), c_double, c_ulong]
_lib.scl_resample_poisson.restype = c_int

def scl_resample_poisson(matrix, lambda, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        lambda: double
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_resample_poisson(matrix, lambda, seed)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_resample_binomial",
    "scl_resample_downsample",
    "scl_resample_downsample_variable",
    "scl_resample_poisson",
]