"""
Auto-generated Python bindings for sampling

Source: scl/binding/c_api/sampling.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_sampling_geometric_sketching(struct scl_sparse_matrix * data, int target_size, scl_index_t * selected_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_geometric_sketching.argtypes = [POINTER(c_void_p), c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_geometric_sketching.restype = c_int

def scl_sampling_geometric_sketching(data, target_size, selected_indices, n_selected, seed):
    """
    Args:
        data: struct scl_sparse_matrix *
        target_size: int
        selected_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_geometric_sketching(data, target_size, selected_indices, n_selected, seed)


# C: int scl_sampling_landmark_selection(struct scl_sparse_matrix * data, int n_landmarks, scl_index_t * landmark_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_landmark_selection.argtypes = [POINTER(c_void_p), c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_landmark_selection.restype = c_int

def scl_sampling_landmark_selection(data, n_landmarks, landmark_indices, n_selected, seed):
    """
    Args:
        data: struct scl_sparse_matrix *
        n_landmarks: int
        landmark_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_landmark_selection(data, n_landmarks, landmark_indices, n_selected, seed)


# C: int scl_sampling_representative_cells(struct scl_sparse_matrix * data, const scl_index_t * cluster_labels, int n_cells, int per_cluster, scl_index_t * representatives, scl_size_t * n_selected, int max_count, unsigned long seed)
_lib.scl_sampling_representative_cells.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_int, POINTER(c_int64), POINTER(c_int), c_int, c_ulong]
_lib.scl_sampling_representative_cells.restype = c_int

def scl_sampling_representative_cells(data, cluster_labels, n_cells, per_cluster, representatives, n_selected, max_count, seed):
    """
    Args:
        data: struct scl_sparse_matrix *
        cluster_labels: const scl_index_t *
        n_cells: int
        per_cluster: int
        representatives: scl_index_t *
        n_selected: scl_size_t *
        max_count: int
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_representative_cells(data, cluster_labels, n_cells, per_cluster, representatives, n_selected, max_count, seed)


# C: int scl_sampling_balanced(const scl_index_t * labels, int n, int target_size, scl_index_t * selected_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_balanced.argtypes = [POINTER(c_int64), c_int, c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_balanced.restype = c_int

def scl_sampling_balanced(labels, n, target_size, selected_indices, n_selected, seed):
    """
    Args:
        labels: const scl_index_t *
        n: int
        target_size: int
        selected_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_balanced(labels, n, target_size, selected_indices, n_selected, seed)


# C: int scl_sampling_stratified(const scl_real_t * values, int n, int n_strata, int target_size, scl_index_t * selected_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_stratified.argtypes = [POINTER(c_double), c_int, c_int, c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_stratified.restype = c_int

def scl_sampling_stratified(values, n, n_strata, target_size, selected_indices, n_selected, seed):
    """
    Args:
        values: const scl_real_t *
        n: int
        n_strata: int
        target_size: int
        selected_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_stratified(values, n, n_strata, target_size, selected_indices, n_selected, seed)


# C: int scl_sampling_uniform(int n, int target_size, scl_index_t * selected_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_uniform.argtypes = [c_int, c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_uniform.restype = c_int

def scl_sampling_uniform(n, target_size, selected_indices, n_selected, seed):
    """
    Args:
        n: int
        target_size: int
        selected_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_uniform(n, target_size, selected_indices, n_selected, seed)


# C: int scl_sampling_importance(const scl_real_t * weights, int n, int target_size, scl_index_t * selected_indices, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_importance.argtypes = [POINTER(c_double), c_int, c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_importance.restype = c_int

def scl_sampling_importance(weights, n, target_size, selected_indices, n_selected, seed):
    """
    Args:
        weights: const scl_real_t *
        n: int
        target_size: int
        selected_indices: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_importance(weights, n, target_size, selected_indices, n_selected, seed)


# C: int scl_sampling_reservoir(int stream_size, int reservoir_size, scl_index_t * reservoir, scl_size_t * n_selected, unsigned long seed)
_lib.scl_sampling_reservoir.argtypes = [c_int, c_int, POINTER(c_int64), POINTER(c_int), c_ulong]
_lib.scl_sampling_reservoir.restype = c_int

def scl_sampling_reservoir(stream_size, reservoir_size, reservoir, n_selected, seed):
    """
    Args:
        stream_size: int
        reservoir_size: int
        reservoir: scl_index_t *
        n_selected: scl_size_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_sampling_reservoir(stream_size, reservoir_size, reservoir, n_selected, seed)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_sampling_balanced",
    "scl_sampling_geometric_sketching",
    "scl_sampling_importance",
    "scl_sampling_landmark_selection",
    "scl_sampling_representative_cells",
    "scl_sampling_reservoir",
    "scl_sampling_stratified",
    "scl_sampling_uniform",
]