"""
Auto-generated Python bindings for scale

Source: scl/binding/c_api/scale.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_scale_standardize(struct scl_sparse_matrix * matrix, const scl_real_t * means, const scl_real_t * stds, int primary_dim, double max_value, int zero_center)
_lib.scl_scale_standardize.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), c_int, c_double, c_int]
_lib.scl_scale_standardize.restype = c_int

def scl_scale_standardize(matrix, means, stds, primary_dim, max_value, zero_center):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        means: const scl_real_t *
        stds: const scl_real_t *
        primary_dim: int
        max_value: double
        zero_center: int
    
    Returns:
        int
    """
    return _lib.scl_scale_standardize(matrix, means, stds, primary_dim, max_value, zero_center)


# C: int scl_scale_rows(struct scl_sparse_matrix * matrix, const scl_real_t * scales, int primary_dim)
_lib.scl_scale_rows.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int]
_lib.scl_scale_rows.restype = c_int

def scl_scale_rows(matrix, scales, primary_dim):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        scales: const scl_real_t *
        primary_dim: int
    
    Returns:
        int
    """
    return _lib.scl_scale_rows(matrix, scales, primary_dim)


# C: int scl_scale_shift_rows(struct scl_sparse_matrix * matrix, const scl_real_t * offsets, int primary_dim)
_lib.scl_scale_shift_rows.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int]
_lib.scl_scale_shift_rows.restype = c_int

def scl_scale_shift_rows(matrix, offsets, primary_dim):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        offsets: const scl_real_t *
        primary_dim: int
    
    Returns:
        int
    """
    return _lib.scl_scale_shift_rows(matrix, offsets, primary_dim)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_scale_rows",
    "scl_scale_shift_rows",
    "scl_scale_standardize",
]