"""
Auto-generated Python bindings for scoring

Source: scl/binding/c_api/scoring.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_scoring_method_t:
    """C enum: scl_scoring_method_t"""
    SCL_SCORING_MEAN = 0
    SCL_SCORING_RANK_BASED = 1
    SCL_SCORING_WEIGHTED = 2
    SCL_SCORING_SEURAT_MODULE = 3
    SCL_SCORING_ZSCORE = 4

class scl_scoring_method_t:
    """C enum: scl_scoring_method_t"""
    SCL_SCORING_MEAN = 0
    SCL_SCORING_RANK_BASED = 1
    SCL_SCORING_WEIGHTED = 2
    SCL_SCORING_SEURAT_MODULE = 3
    SCL_SCORING_ZSCORE = 4

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_scoring_method_t = c_void_p  # typedef enum scl_scoring_method_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_scoring_gene_set_score(struct scl_sparse_matrix * expression, const scl_index_t * gene_set, int n_genes_in_set, scl_real_t * scores, int n_cells, long n_genes, scl_scoring_method_t method, double quantile)
_lib.scl_scoring_gene_set_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), c_int, c_long, c_void_p, c_double]
_lib.scl_scoring_gene_set_score.restype = c_int

def scl_scoring_gene_set_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, method, quantile):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_set: const scl_index_t *
        n_genes_in_set: int
        scores: scl_real_t *
        n_cells: int
        n_genes: long
        method: scl_scoring_method_t
        quantile: double
    
    Returns:
        int
    """
    return _lib.scl_scoring_gene_set_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, method, quantile)


# C: int scl_scoring_mean_score(struct scl_sparse_matrix * expression, const scl_index_t * gene_set, int n_genes_in_set, scl_real_t * scores, int n_cells, long n_genes)
_lib.scl_scoring_mean_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), c_int, c_long]
_lib.scl_scoring_mean_score.restype = c_int

def scl_scoring_mean_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_set: const scl_index_t *
        n_genes_in_set: int
        scores: scl_real_t *
        n_cells: int
        n_genes: long
    
    Returns:
        int
    """
    return _lib.scl_scoring_mean_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes)


# C: int scl_scoring_auc_score(struct scl_sparse_matrix * expression, const scl_index_t * gene_set, int n_genes_in_set, scl_real_t * scores, int n_cells, long n_genes, double quantile)
_lib.scl_scoring_auc_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), c_int, c_long, c_double]
_lib.scl_scoring_auc_score.restype = c_int

def scl_scoring_auc_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, quantile):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_set: const scl_index_t *
        n_genes_in_set: int
        scores: scl_real_t *
        n_cells: int
        n_genes: long
        quantile: double
    
    Returns:
        int
    """
    return _lib.scl_scoring_auc_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, quantile)


# C: int scl_scoring_module_score(struct scl_sparse_matrix * expression, const scl_index_t * gene_set, int n_genes_in_set, scl_real_t * scores, int n_cells, long n_genes, long n_control_per_gene, long n_bins)
_lib.scl_scoring_module_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), c_int, c_long, c_long, c_long]
_lib.scl_scoring_module_score.restype = c_int

def scl_scoring_module_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, n_control_per_gene, n_bins):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_set: const scl_index_t *
        n_genes_in_set: int
        scores: scl_real_t *
        n_cells: int
        n_genes: long
        n_control_per_gene: long
        n_bins: long
    
    Returns:
        int
    """
    return _lib.scl_scoring_module_score(expression, gene_set, n_genes_in_set, scores, n_cells, n_genes, n_control_per_gene, n_bins)


# C: int scl_scoring_differential_score(struct scl_sparse_matrix * expression, const scl_index_t * positive_genes, int n_positive, const scl_index_t * negative_genes, int n_negative, scl_real_t * scores, int n_cells, long n_genes)
_lib.scl_scoring_differential_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int64), c_int, POINTER(c_double), c_int, c_long]
_lib.scl_scoring_differential_score.restype = c_int

def scl_scoring_differential_score(expression, positive_genes, n_positive, negative_genes, n_negative, scores, n_cells, n_genes):
    """
    Args:
        expression: struct scl_sparse_matrix *
        positive_genes: const scl_index_t *
        n_positive: int
        negative_genes: const scl_index_t *
        n_negative: int
        scores: scl_real_t *
        n_cells: int
        n_genes: long
    
    Returns:
        int
    """
    return _lib.scl_scoring_differential_score(expression, positive_genes, n_positive, negative_genes, n_negative, scores, n_cells, n_genes)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_scoring_auc_score",
    "scl_scoring_differential_score",
    "scl_scoring_gene_set_score",
    "scl_scoring_mean_score",
    "scl_scoring_method_t",
    "scl_scoring_method_t",
    "scl_scoring_method_t",
    "scl_scoring_module_score",
]