"""
Auto-generated Python bindings for slice

Source: scl/binding/c_api/slice.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_slice_inspect_primary(struct scl_sparse_matrix * matrix, const scl_index_t * keep_indices, int n_keep, scl_index_t * out_nnz)
_lib.scl_slice_inspect_primary.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int64)]
_lib.scl_slice_inspect_primary.restype = c_int

def scl_slice_inspect_primary(matrix, keep_indices, n_keep, out_nnz):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        keep_indices: const scl_index_t *
        n_keep: int
        out_nnz: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_slice_inspect_primary(matrix, keep_indices, n_keep, out_nnz)


# C: int scl_slice_primary(struct scl_sparse_matrix * matrix, const scl_index_t * keep_indices, int n_keep, scl_sparse_t * out_matrix)
_lib.scl_slice_primary.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_slice_primary.restype = c_int

def scl_slice_primary(matrix, keep_indices, n_keep, out_matrix):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        keep_indices: const scl_index_t *
        n_keep: int
        out_matrix: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_slice_primary(matrix, keep_indices, n_keep, out_matrix)


# C: int scl_slice_inspect_filter_secondary(struct scl_sparse_matrix * matrix, const uint8_t * mask, int secondary_dim, scl_index_t * out_nnz)
_lib.scl_slice_inspect_filter_secondary.argtypes = [POINTER(c_void_p), POINTER(c_uint8), c_int, POINTER(c_int64)]
_lib.scl_slice_inspect_filter_secondary.restype = c_int

def scl_slice_inspect_filter_secondary(matrix, mask, secondary_dim, out_nnz):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        mask: const uint8_t *
        secondary_dim: int
        out_nnz: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_slice_inspect_filter_secondary(matrix, mask, secondary_dim, out_nnz)


# C: int scl_slice_filter_secondary(struct scl_sparse_matrix * matrix, const uint8_t * mask, int secondary_dim, scl_sparse_t * out_matrix)
_lib.scl_slice_filter_secondary.argtypes = [POINTER(c_void_p), POINTER(c_uint8), c_int, POINTER(POINTER(scl_sparse_matrix))]
_lib.scl_slice_filter_secondary.restype = c_int

def scl_slice_filter_secondary(matrix, mask, secondary_dim, out_matrix):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        mask: const uint8_t *
        secondary_dim: int
        out_matrix: scl_sparse_t *
    
    Returns:
        int
    """
    return _lib.scl_slice_filter_secondary(matrix, mask, secondary_dim, out_matrix)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_slice_filter_secondary",
    "scl_slice_inspect_filter_secondary",
    "scl_slice_inspect_primary",
    "scl_slice_primary",
]