"""
Auto-generated Python bindings for sparse_opt

Source: scl/binding/c_api/sparse_opt.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_regularization_type_t:
    """C enum: scl_regularization_type_t"""
    SCL_REG_L1 = 0
    SCL_REG_L2 = 1
    SCL_REG_ELASTIC_NET = 2
    SCL_REG_SCAD = 3
    SCL_REG_MCP = 4

class scl_regularization_type_t:
    """C enum: scl_regularization_type_t"""
    SCL_REG_L1 = 0
    SCL_REG_L2 = 1
    SCL_REG_ELASTIC_NET = 2
    SCL_REG_SCAD = 3
    SCL_REG_MCP = 4

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_regularization_type_t = c_void_p  # typedef enum scl_regularization_type_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_sparse_opt_prox_l1(scl_real_t * x, int n, double lambda)
_lib.scl_sparse_opt_prox_l1.argtypes = [POINTER(c_double), c_int, c_double]
_lib.scl_sparse_opt_prox_l1.restype = c_int

def scl_sparse_opt_prox_l1(x, n, lambda):
    """
    Args:
        x: scl_real_t *
        n: int
        lambda: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_prox_l1(x, n, lambda)


# C: int scl_sparse_opt_prox_elastic_net(scl_real_t * x, int n, double lambda, double l1_ratio)
_lib.scl_sparse_opt_prox_elastic_net.argtypes = [POINTER(c_double), c_int, c_double, c_double]
_lib.scl_sparse_opt_prox_elastic_net.restype = c_int

def scl_sparse_opt_prox_elastic_net(x, n, lambda, l1_ratio):
    """
    Args:
        x: scl_real_t *
        n: int
        lambda: double
        l1_ratio: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_prox_elastic_net(x, n, lambda, l1_ratio)


# C: int scl_sparse_opt_lasso_coordinate_descent(struct scl_sparse_matrix * X, const scl_real_t * y, double alpha, scl_real_t * coefficients, long max_iter, double tol)
_lib.scl_sparse_opt_lasso_coordinate_descent.argtypes = [POINTER(c_void_p), POINTER(c_double), c_double, POINTER(c_double), c_long, c_double]
_lib.scl_sparse_opt_lasso_coordinate_descent.restype = c_int

def scl_sparse_opt_lasso_coordinate_descent(X, y, alpha, coefficients, max_iter, tol):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        alpha: double
        coefficients: scl_real_t *
        max_iter: long
        tol: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_lasso_coordinate_descent(X, y, alpha, coefficients, max_iter, tol)


# C: int scl_sparse_opt_elastic_net_coordinate_descent(struct scl_sparse_matrix * X, const scl_real_t * y, double alpha, double l1_ratio, scl_real_t * coefficients, long max_iter, double tol)
_lib.scl_sparse_opt_elastic_net_coordinate_descent.argtypes = [POINTER(c_void_p), POINTER(c_double), c_double, c_double, POINTER(c_double), c_long, c_double]
_lib.scl_sparse_opt_elastic_net_coordinate_descent.restype = c_int

def scl_sparse_opt_elastic_net_coordinate_descent(X, y, alpha, l1_ratio, coefficients, max_iter, tol):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        alpha: double
        l1_ratio: double
        coefficients: scl_real_t *
        max_iter: long
        tol: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_elastic_net_coordinate_descent(X, y, alpha, l1_ratio, coefficients, max_iter, tol)


# C: int scl_sparse_opt_fista_lasso(struct scl_sparse_matrix * X, const scl_real_t * y, double alpha, scl_real_t * coefficients, long max_iter, double tol)
_lib.scl_sparse_opt_fista_lasso.argtypes = [POINTER(c_void_p), POINTER(c_double), c_double, POINTER(c_double), c_long, c_double]
_lib.scl_sparse_opt_fista_lasso.restype = c_int

def scl_sparse_opt_fista_lasso(X, y, alpha, coefficients, max_iter, tol):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        alpha: double
        coefficients: scl_real_t *
        max_iter: long
        tol: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_fista_lasso(X, y, alpha, coefficients, max_iter, tol)


# C: int scl_sparse_opt_iht(struct scl_sparse_matrix * X, const scl_real_t * y, long sparsity_level, scl_real_t * coefficients, long max_iter)
_lib.scl_sparse_opt_iht.argtypes = [POINTER(c_void_p), POINTER(c_double), c_long, POINTER(c_double), c_long]
_lib.scl_sparse_opt_iht.restype = c_int

def scl_sparse_opt_iht(X, y, sparsity_level, coefficients, max_iter):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        sparsity_level: long
        coefficients: scl_real_t *
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_iht(X, y, sparsity_level, coefficients, max_iter)


# C: int scl_sparse_opt_lasso_path(struct scl_sparse_matrix * X, const scl_real_t * y, const scl_real_t * alphas, int n_alphas, scl_real_t * coefficient_paths, long max_iter)
_lib.scl_sparse_opt_lasso_path.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_double), c_int, POINTER(c_double), c_long]
_lib.scl_sparse_opt_lasso_path.restype = c_int

def scl_sparse_opt_lasso_path(X, y, alphas, n_alphas, coefficient_paths, max_iter):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        alphas: const scl_real_t *
        n_alphas: int
        coefficient_paths: scl_real_t *
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_lasso_path(X, y, alphas, n_alphas, coefficient_paths, max_iter)


# C: int scl_sparse_opt_proximal_gradient(struct scl_sparse_matrix * X, const scl_real_t * y, double alpha, scl_regularization_type_t reg_type, scl_real_t * coefficients, long max_iter, double tol)
_lib.scl_sparse_opt_proximal_gradient.argtypes = [POINTER(c_void_p), POINTER(c_double), c_double, c_void_p, POINTER(c_double), c_long, c_double]
_lib.scl_sparse_opt_proximal_gradient.restype = c_int

def scl_sparse_opt_proximal_gradient(X, y, alpha, reg_type, coefficients, max_iter, tol):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        alpha: double
        reg_type: scl_regularization_type_t
        coefficients: scl_real_t *
        max_iter: long
        tol: double
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_proximal_gradient(X, y, alpha, reg_type, coefficients, max_iter, tol)


# C: int scl_sparse_opt_group_lasso(struct scl_sparse_matrix * X, const scl_real_t * y, const scl_index_t * group_indices, const scl_index_t * group_offsets, long n_groups, double alpha, scl_real_t * coefficients, long max_iter)
_lib.scl_sparse_opt_group_lasso.argtypes = [POINTER(c_void_p), POINTER(c_double), POINTER(c_int64), POINTER(c_int64), c_long, c_double, POINTER(c_double), c_long]
_lib.scl_sparse_opt_group_lasso.restype = c_int

def scl_sparse_opt_group_lasso(X, y, group_indices, group_offsets, n_groups, alpha, coefficients, max_iter):
    """
    Args:
        X: struct scl_sparse_matrix *
        y: const scl_real_t *
        group_indices: const scl_index_t *
        group_offsets: const scl_index_t *
        n_groups: long
        alpha: double
        coefficients: scl_real_t *
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_group_lasso(X, y, group_indices, group_offsets, n_groups, alpha, coefficients, max_iter)


# C: int scl_sparse_opt_logistic_regression(struct scl_sparse_matrix * X, const scl_index_t * y_binary, double alpha, scl_real_t * coefficients, long max_iter)
_lib.scl_sparse_opt_logistic_regression.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_double, POINTER(c_double), c_long]
_lib.scl_sparse_opt_logistic_regression.restype = c_int

def scl_sparse_opt_logistic_regression(X, y_binary, alpha, coefficients, max_iter):
    """
    Args:
        X: struct scl_sparse_matrix *
        y_binary: const scl_index_t *
        alpha: double
        coefficients: scl_real_t *
        max_iter: long
    
    Returns:
        int
    """
    return _lib.scl_sparse_opt_logistic_regression(X, y_binary, alpha, coefficients, max_iter)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_regularization_type_t",
    "scl_regularization_type_t",
    "scl_regularization_type_t",
    "scl_sparse_opt_elastic_net_coordinate_descent",
    "scl_sparse_opt_fista_lasso",
    "scl_sparse_opt_group_lasso",
    "scl_sparse_opt_iht",
    "scl_sparse_opt_lasso_coordinate_descent",
    "scl_sparse_opt_lasso_path",
    "scl_sparse_opt_logistic_regression",
    "scl_sparse_opt_prox_elastic_net",
    "scl_sparse_opt_prox_l1",
    "scl_sparse_opt_proximal_gradient",
]