"""
Auto-generated Python bindings for spatial

Source: scl/binding/c_api/spatial.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_spatial_weight_sum(struct scl_sparse_matrix * graph, scl_real_t * weight_sum)
_lib.scl_spatial_weight_sum.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_spatial_weight_sum.restype = c_int

def scl_spatial_weight_sum(graph, weight_sum):
    """
    Args:
        graph: struct scl_sparse_matrix *
        weight_sum: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_spatial_weight_sum(graph, weight_sum)


# C: int scl_spatial_morans_i(struct scl_sparse_matrix * graph, struct scl_sparse_matrix * features, scl_real_t * output)
_lib.scl_spatial_morans_i.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_double)]
_lib.scl_spatial_morans_i.restype = c_int

def scl_spatial_morans_i(graph, features, output):
    """
    Args:
        graph: struct scl_sparse_matrix *
        features: struct scl_sparse_matrix *
        output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_spatial_morans_i(graph, features, output)


# C: int scl_spatial_gearys_c(struct scl_sparse_matrix * graph, struct scl_sparse_matrix * features, scl_real_t * output)
_lib.scl_spatial_gearys_c.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_double)]
_lib.scl_spatial_gearys_c.restype = c_int

def scl_spatial_gearys_c(graph, features, output):
    """
    Args:
        graph: struct scl_sparse_matrix *
        features: struct scl_sparse_matrix *
        output: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_spatial_gearys_c(graph, features, output)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_spatial_gearys_c",
    "scl_spatial_morans_i",
    "scl_spatial_weight_sum",
]