"""
Auto-generated Python bindings for state

Source: scl/binding/c_api/state.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_state_stemness_score(struct scl_sparse_matrix * expression, const scl_index_t * stemness_genes, int n_stemness_genes, scl_real_t * scores)
_lib.scl_state_stemness_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_state_stemness_score.restype = c_int

def scl_state_stemness_score(expression, stemness_genes, n_stemness_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        stemness_genes: const scl_index_t *
        n_stemness_genes: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_stemness_score(expression, stemness_genes, n_stemness_genes, scores)


# C: int scl_state_differentiation_potential(struct scl_sparse_matrix * expression, scl_real_t * potency_scores)
_lib.scl_state_differentiation_potential.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_state_differentiation_potential.restype = c_int

def scl_state_differentiation_potential(expression, potency_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        potency_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_differentiation_potential(expression, potency_scores)


# C: int scl_state_proliferation_score(struct scl_sparse_matrix * expression, const scl_index_t * proliferation_genes, int n_proliferation_genes, scl_real_t * scores)
_lib.scl_state_proliferation_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_state_proliferation_score.restype = c_int

def scl_state_proliferation_score(expression, proliferation_genes, n_proliferation_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        proliferation_genes: const scl_index_t *
        n_proliferation_genes: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_proliferation_score(expression, proliferation_genes, n_proliferation_genes, scores)


# C: int scl_state_stress_score(struct scl_sparse_matrix * expression, const scl_index_t * stress_genes, int n_stress_genes, scl_real_t * scores)
_lib.scl_state_stress_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_state_stress_score.restype = c_int

def scl_state_stress_score(expression, stress_genes, n_stress_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        stress_genes: const scl_index_t *
        n_stress_genes: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_stress_score(expression, stress_genes, n_stress_genes, scores)


# C: int scl_state_entropy(struct scl_sparse_matrix * expression, scl_real_t * entropy_scores)
_lib.scl_state_entropy.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_state_entropy.restype = c_int

def scl_state_entropy(expression, entropy_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        entropy_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_entropy(expression, entropy_scores)


# C: int scl_state_cell_cycle_score(struct scl_sparse_matrix * expression, const scl_index_t * s_genes, int n_s_genes, const scl_index_t * g2m_genes, int n_g2m_genes, scl_real_t * s_scores, scl_real_t * g2m_scores, scl_index_t * phase_labels)
_lib.scl_state_cell_cycle_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int64), c_int, POINTER(c_double), POINTER(c_double), POINTER(c_int64)]
_lib.scl_state_cell_cycle_score.restype = c_int

def scl_state_cell_cycle_score(expression, s_genes, n_s_genes, g2m_genes, n_g2m_genes, s_scores, g2m_scores, phase_labels):
    """
    Args:
        expression: struct scl_sparse_matrix *
        s_genes: const scl_index_t *
        n_s_genes: int
        g2m_genes: const scl_index_t *
        n_g2m_genes: int
        s_scores: scl_real_t *
        g2m_scores: scl_real_t *
        phase_labels: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_state_cell_cycle_score(expression, s_genes, n_s_genes, g2m_genes, n_g2m_genes, s_scores, g2m_scores, phase_labels)


# C: int scl_state_quiescence_score(struct scl_sparse_matrix * expression, const scl_index_t * quiescence_genes, int n_quiescence_genes, const scl_index_t * proliferation_genes, int n_proliferation_genes, scl_real_t * scores)
_lib.scl_state_quiescence_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_state_quiescence_score.restype = c_int

def scl_state_quiescence_score(expression, quiescence_genes, n_quiescence_genes, proliferation_genes, n_proliferation_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        quiescence_genes: const scl_index_t *
        n_quiescence_genes: int
        proliferation_genes: const scl_index_t *
        n_proliferation_genes: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_quiescence_score(expression, quiescence_genes, n_quiescence_genes, proliferation_genes, n_proliferation_genes, scores)


# C: int scl_state_metabolic_score(struct scl_sparse_matrix * expression, const scl_index_t * glycolysis_genes, int n_glycolysis_genes, const scl_index_t * oxphos_genes, int n_oxphos_genes, scl_real_t * glycolysis_scores, scl_real_t * oxphos_scores)
_lib.scl_state_metabolic_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_int64), c_int, POINTER(c_double), POINTER(c_double)]
_lib.scl_state_metabolic_score.restype = c_int

def scl_state_metabolic_score(expression, glycolysis_genes, n_glycolysis_genes, oxphos_genes, n_oxphos_genes, glycolysis_scores, oxphos_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        glycolysis_genes: const scl_index_t *
        n_glycolysis_genes: int
        oxphos_genes: const scl_index_t *
        n_oxphos_genes: int
        glycolysis_scores: scl_real_t *
        oxphos_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_metabolic_score(expression, glycolysis_genes, n_glycolysis_genes, oxphos_genes, n_oxphos_genes, glycolysis_scores, oxphos_scores)


# C: int scl_state_apoptosis_score(struct scl_sparse_matrix * expression, const scl_index_t * apoptosis_genes, int n_apoptosis_genes, scl_real_t * scores)
_lib.scl_state_apoptosis_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double)]
_lib.scl_state_apoptosis_score.restype = c_int

def scl_state_apoptosis_score(expression, apoptosis_genes, n_apoptosis_genes, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        apoptosis_genes: const scl_index_t *
        n_apoptosis_genes: int
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_apoptosis_score(expression, apoptosis_genes, n_apoptosis_genes, scores)


# C: int scl_state_signature_score(struct scl_sparse_matrix * expression, const scl_index_t * gene_indices, int n_signature, const scl_real_t * gene_weights, scl_real_t * scores)
_lib.scl_state_signature_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, POINTER(c_double), POINTER(c_double)]
_lib.scl_state_signature_score.restype = c_int

def scl_state_signature_score(expression, gene_indices, n_signature, gene_weights, scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_indices: const scl_index_t *
        n_signature: int
        gene_weights: const scl_real_t *
        scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_signature_score(expression, gene_indices, n_signature, gene_weights, scores)


# C: int scl_state_multi_signature_score(struct scl_sparse_matrix * expression, const scl_index_t * signature_gene_indices, const scl_size_t * signature_offsets, int n_signatures, scl_real_t * score_matrix)
_lib.scl_state_multi_signature_score.argtypes = [POINTER(c_void_p), POINTER(c_int64), POINTER(c_int), c_int, POINTER(c_double)]
_lib.scl_state_multi_signature_score.restype = c_int

def scl_state_multi_signature_score(expression, signature_gene_indices, signature_offsets, n_signatures, score_matrix):
    """
    Args:
        expression: struct scl_sparse_matrix *
        signature_gene_indices: const scl_index_t *
        signature_offsets: const scl_size_t *
        n_signatures: int
        score_matrix: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_multi_signature_score(expression, signature_gene_indices, signature_offsets, n_signatures, score_matrix)


# C: int scl_state_transcriptional_diversity(struct scl_sparse_matrix * expression, scl_real_t * diversity_scores)
_lib.scl_state_transcriptional_diversity.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_state_transcriptional_diversity.restype = c_int

def scl_state_transcriptional_diversity(expression, diversity_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        diversity_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_transcriptional_diversity(expression, diversity_scores)


# C: int scl_state_expression_complexity(struct scl_sparse_matrix * expression, double expression_threshold, scl_real_t * complexity_scores)
_lib.scl_state_expression_complexity.argtypes = [POINTER(c_void_p), c_double, POINTER(c_double)]
_lib.scl_state_expression_complexity.restype = c_int

def scl_state_expression_complexity(expression, expression_threshold, complexity_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        expression_threshold: double
        complexity_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_expression_complexity(expression, expression_threshold, complexity_scores)


# C: int scl_state_combined_score(struct scl_sparse_matrix * expression, const scl_index_t *const * gene_sets, const scl_size_t * gene_set_sizes, const scl_real_t * weights, int n_gene_sets, scl_real_t * combined_scores)
_lib.scl_state_combined_score.argtypes = [POINTER(c_void_p), POINTER(POINTER(c_int64)), POINTER(c_int), POINTER(c_double), c_int, POINTER(c_double)]
_lib.scl_state_combined_score.restype = c_int

def scl_state_combined_score(expression, gene_sets, gene_set_sizes, weights, n_gene_sets, combined_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        gene_sets: const scl_index_t *const *
        gene_set_sizes: const scl_size_t *
        weights: const scl_real_t *
        n_gene_sets: int
        combined_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_state_combined_score(expression, gene_sets, gene_set_sizes, weights, n_gene_sets, combined_scores)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_state_apoptosis_score",
    "scl_state_cell_cycle_score",
    "scl_state_combined_score",
    "scl_state_differentiation_potential",
    "scl_state_entropy",
    "scl_state_expression_complexity",
    "scl_state_metabolic_score",
    "scl_state_multi_signature_score",
    "scl_state_proliferation_score",
    "scl_state_quiescence_score",
    "scl_state_signature_score",
    "scl_state_stemness_score",
    "scl_state_stress_score",
    "scl_state_transcriptional_diversity",
]