"""
Auto-generated Python bindings for subpopulation

Source: scl/binding/c_api/subpopulation.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_subpopulation_subclustering(struct scl_sparse_matrix * expression, const scl_index_t * parent_labels, int n_cells, long parent_cluster, int n_subclusters, scl_index_t * subcluster_labels, unsigned long seed)
_lib.scl_subpopulation_subclustering.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_long, c_int, POINTER(c_int64), c_ulong]
_lib.scl_subpopulation_subclustering.restype = c_int

def scl_subpopulation_subclustering(expression, parent_labels, n_cells, parent_cluster, n_subclusters, subcluster_labels, seed):
    """
    Args:
        expression: struct scl_sparse_matrix *
        parent_labels: const scl_index_t *
        n_cells: int
        parent_cluster: long
        n_subclusters: int
        subcluster_labels: scl_index_t *
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_subpopulation_subclustering(expression, parent_labels, n_cells, parent_cluster, n_subclusters, subcluster_labels, seed)


# C: int scl_subpopulation_cluster_stability(struct scl_sparse_matrix * expression, const scl_index_t * original_labels, int n_cells, int n_bootstraps, scl_real_t * stability_scores, int stability_scores_size, unsigned long seed)
_lib.scl_subpopulation_cluster_stability.argtypes = [POINTER(c_void_p), POINTER(c_int64), c_int, c_int, POINTER(c_double), c_int, c_ulong]
_lib.scl_subpopulation_cluster_stability.restype = c_int

def scl_subpopulation_cluster_stability(expression, original_labels, n_cells, n_bootstraps, stability_scores, stability_scores_size, seed):
    """
    Args:
        expression: struct scl_sparse_matrix *
        original_labels: const scl_index_t *
        n_cells: int
        n_bootstraps: int
        stability_scores: scl_real_t *
        stability_scores_size: int
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_subpopulation_cluster_stability(expression, original_labels, n_cells, n_bootstraps, stability_scores, stability_scores_size, seed)


# C: int scl_subpopulation_cluster_purity(const scl_index_t * cluster_labels, const scl_index_t * true_labels, int n_cells, scl_real_t * purity_per_cluster, int purity_size)
_lib.scl_subpopulation_cluster_purity.argtypes = [POINTER(c_int64), POINTER(c_int64), c_int, POINTER(c_double), c_int]
_lib.scl_subpopulation_cluster_purity.restype = c_int

def scl_subpopulation_cluster_purity(cluster_labels, true_labels, n_cells, purity_per_cluster, purity_size):
    """
    Args:
        cluster_labels: const scl_index_t *
        true_labels: const scl_index_t *
        n_cells: int
        purity_per_cluster: scl_real_t *
        purity_size: int
    
    Returns:
        int
    """
    return _lib.scl_subpopulation_cluster_purity(cluster_labels, true_labels, n_cells, purity_per_cluster, purity_size)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_subpopulation_cluster_purity",
    "scl_subpopulation_cluster_stability",
    "scl_subpopulation_subclustering",
]