"""
Auto-generated Python bindings for tissue

Source: scl/binding/c_api/tissue.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_tissue_architecture(const scl_real_t * coordinates, int n_cells, int n_dims, const scl_index_t * cell_types, scl_real_t * density, scl_real_t * heterogeneity, scl_real_t * clustering_coef, int n_neighbors)
_lib.scl_tissue_architecture.argtypes = [POINTER(c_double), c_int, c_int, POINTER(c_int64), POINTER(c_double), POINTER(c_double), POINTER(c_double), c_int]
_lib.scl_tissue_architecture.restype = c_int

def scl_tissue_architecture(coordinates, n_cells, n_dims, cell_types, density, heterogeneity, clustering_coef, n_neighbors):
    """
    Args:
        coordinates: const scl_real_t *
        n_cells: int
        n_dims: int
        cell_types: const scl_index_t *
        density: scl_real_t *
        heterogeneity: scl_real_t *
        clustering_coef: scl_real_t *
        n_neighbors: int
    
    Returns:
        int
    """
    return _lib.scl_tissue_architecture(coordinates, n_cells, n_dims, cell_types, density, heterogeneity, clustering_coef, n_neighbors)


# C: int scl_tissue_layer_assignment(const scl_real_t * coordinates, int n_cells, int n_dims, long n_layers, scl_index_t * layer_labels, long reference_dim)
_lib.scl_tissue_layer_assignment.argtypes = [POINTER(c_double), c_int, c_int, c_long, POINTER(c_int64), c_long]
_lib.scl_tissue_layer_assignment.restype = c_int

def scl_tissue_layer_assignment(coordinates, n_cells, n_dims, n_layers, layer_labels, reference_dim):
    """
    Args:
        coordinates: const scl_real_t *
        n_cells: int
        n_dims: int
        n_layers: long
        layer_labels: scl_index_t *
        reference_dim: long
    
    Returns:
        int
    """
    return _lib.scl_tissue_layer_assignment(coordinates, n_cells, n_dims, n_layers, layer_labels, reference_dim)


# C: int scl_tissue_radial_layer_assignment(const scl_real_t * coordinates, int n_cells, int n_dims, const scl_real_t * center, long n_layers, scl_index_t * layer_labels)
_lib.scl_tissue_radial_layer_assignment.argtypes = [POINTER(c_double), c_int, c_int, POINTER(c_double), c_long, POINTER(c_int64)]
_lib.scl_tissue_radial_layer_assignment.restype = c_int

def scl_tissue_radial_layer_assignment(coordinates, n_cells, n_dims, center, n_layers, layer_labels):
    """
    Args:
        coordinates: const scl_real_t *
        n_cells: int
        n_dims: int
        center: const scl_real_t *
        n_layers: long
        layer_labels: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_tissue_radial_layer_assignment(coordinates, n_cells, n_dims, center, n_layers, layer_labels)


# C: int scl_tissue_zonation_score(struct scl_sparse_matrix * expression, const scl_real_t * coordinates, int n_dims, const scl_real_t * reference_point, scl_real_t * zonation_scores)
_lib.scl_tissue_zonation_score.argtypes = [POINTER(c_void_p), POINTER(c_double), c_int, POINTER(c_double), POINTER(c_double)]
_lib.scl_tissue_zonation_score.restype = c_int

def scl_tissue_zonation_score(expression, coordinates, n_dims, reference_point, zonation_scores):
    """
    Args:
        expression: struct scl_sparse_matrix *
        coordinates: const scl_real_t *
        n_dims: int
        reference_point: const scl_real_t *
        zonation_scores: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_tissue_zonation_score(expression, coordinates, n_dims, reference_point, zonation_scores)


# C: int scl_tissue_morphological_features(const scl_real_t * coordinates, int n_cells, int n_dims, const scl_index_t * labels, int n_groups, scl_real_t * area, scl_real_t * perimeter, scl_real_t * circularity, scl_real_t * eccentricity)
_lib.scl_tissue_morphological_features.argtypes = [POINTER(c_double), c_int, c_int, POINTER(c_int64), c_int, POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double)]
_lib.scl_tissue_morphological_features.restype = c_int

def scl_tissue_morphological_features(coordinates, n_cells, n_dims, labels, n_groups, area, perimeter, circularity, eccentricity):
    """
    Args:
        coordinates: const scl_real_t *
        n_cells: int
        n_dims: int
        labels: const scl_index_t *
        n_groups: int
        area: scl_real_t *
        perimeter: scl_real_t *
        circularity: scl_real_t *
        eccentricity: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_tissue_morphological_features(coordinates, n_cells, n_dims, labels, n_groups, area, perimeter, circularity, eccentricity)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_tissue_architecture",
    "scl_tissue_layer_assignment",
    "scl_tissue_morphological_features",
    "scl_tissue_radial_layer_assignment",
    "scl_tissue_zonation_score",
]