"""
Auto-generated Python bindings for ttest

Source: scl/binding/c_api/ttest.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_ttest(struct scl_sparse_matrix * matrix, const int32_t * group_ids, int n_cells, scl_real_t * out_t_stats, int t_stats_size, scl_real_t * out_p_values, int p_values_size, scl_real_t * out_log2_fc, int log2_fc_size, int use_welch)
_lib.scl_ttest.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, c_int]
_lib.scl_ttest.restype = c_int

def scl_ttest(matrix, group_ids, n_cells, out_t_stats, t_stats_size, out_p_values, p_values_size, out_log2_fc, log2_fc_size, use_welch):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        n_cells: int
        out_t_stats: scl_real_t *
        t_stats_size: int
        out_p_values: scl_real_t *
        p_values_size: int
        out_log2_fc: scl_real_t *
        log2_fc_size: int
        use_welch: int
    
    Returns:
        int
    """
    return _lib.scl_ttest(matrix, group_ids, n_cells, out_t_stats, t_stats_size, out_p_values, p_values_size, out_log2_fc, log2_fc_size, use_welch)


# C: int scl_ttest_compute_group_stats(struct scl_sparse_matrix * matrix, const int32_t * group_ids, int n_cells, int n_groups, scl_real_t * out_means, int means_size, scl_real_t * out_vars, int vars_size, scl_size_t * out_counts)
_lib.scl_ttest_compute_group_stats.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, c_int, POINTER(c_double), c_int, POINTER(c_double), c_int, POINTER(c_int)]
_lib.scl_ttest_compute_group_stats.restype = c_int

def scl_ttest_compute_group_stats(matrix, group_ids, n_cells, n_groups, out_means, means_size, out_vars, vars_size, out_counts):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        n_cells: int
        n_groups: int
        out_means: scl_real_t *
        means_size: int
        out_vars: scl_real_t *
        vars_size: int
        out_counts: scl_size_t *
    
    Returns:
        int
    """
    return _lib.scl_ttest_compute_group_stats(matrix, group_ids, n_cells, n_groups, out_means, means_size, out_vars, vars_size, out_counts)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_ttest",
    "scl_ttest_compute_group_stats",
]