"""
Auto-generated Python bindings for velocity

Source: scl/binding/c_api/velocity.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_velocity_model_t:
    """C enum: scl_velocity_model_t"""
    SCL_VELOCITY_STEADY_STATE = 0
    SCL_VELOCITY_DYNAMICAL = 1
    SCL_VELOCITY_STOCHASTIC = 2

class scl_velocity_model_t:
    """C enum: scl_velocity_model_t"""
    SCL_VELOCITY_STEADY_STATE = 0
    SCL_VELOCITY_DYNAMICAL = 1
    SCL_VELOCITY_STOCHASTIC = 2

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_velocity_model_t = c_void_p  # typedef enum scl_velocity_model_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_velocity_fit_kinetics(struct scl_sparse_matrix * spliced, struct scl_sparse_matrix * unspliced, long n_cells, long n_genes, scl_real_t * gamma, scl_real_t * r2, scl_velocity_model_t model)
_lib.scl_velocity_fit_kinetics.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, POINTER(c_double), POINTER(c_double), c_void_p]
_lib.scl_velocity_fit_kinetics.restype = c_int

def scl_velocity_fit_kinetics(spliced, unspliced, n_cells, n_genes, gamma, r2, model):
    """
    Args:
        spliced: struct scl_sparse_matrix *
        unspliced: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        gamma: scl_real_t *
        r2: scl_real_t *
        model: scl_velocity_model_t
    
    Returns:
        int
    """
    return _lib.scl_velocity_fit_kinetics(spliced, unspliced, n_cells, n_genes, gamma, r2, model)


# C: int scl_velocity_compute(struct scl_sparse_matrix * spliced, struct scl_sparse_matrix * unspliced, const scl_real_t * gamma, long n_cells, long n_genes, scl_real_t * velocity_out)
_lib.scl_velocity_compute.argtypes = [POINTER(c_void_p), POINTER(c_void_p), POINTER(c_double), c_long, c_long, POINTER(c_double)]
_lib.scl_velocity_compute.restype = c_int

def scl_velocity_compute(spliced, unspliced, gamma, n_cells, n_genes, velocity_out):
    """
    Args:
        spliced: struct scl_sparse_matrix *
        unspliced: struct scl_sparse_matrix *
        gamma: const scl_real_t *
        n_cells: long
        n_genes: long
        velocity_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_velocity_compute(spliced, unspliced, gamma, n_cells, n_genes, velocity_out)


# C: int scl_velocity_splice_ratio(struct scl_sparse_matrix * spliced, struct scl_sparse_matrix * unspliced, long n_cells, long n_genes, scl_real_t * ratio_out)
_lib.scl_velocity_splice_ratio.argtypes = [POINTER(c_void_p), POINTER(c_void_p), c_long, c_long, POINTER(c_double)]
_lib.scl_velocity_splice_ratio.restype = c_int

def scl_velocity_splice_ratio(spliced, unspliced, n_cells, n_genes, ratio_out):
    """
    Args:
        spliced: struct scl_sparse_matrix *
        unspliced: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        ratio_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_velocity_splice_ratio(spliced, unspliced, n_cells, n_genes, ratio_out)


# C: int scl_velocity_graph(const scl_real_t * velocity, const scl_real_t * expression, struct scl_sparse_matrix * knn, long n_cells, long n_genes, scl_real_t * transition_probs, long k_neighbors)
_lib.scl_velocity_graph.argtypes = [POINTER(c_double), POINTER(c_double), POINTER(c_void_p), c_long, c_long, POINTER(c_double), c_long]
_lib.scl_velocity_graph.restype = c_int

def scl_velocity_graph(velocity, expression, knn, n_cells, n_genes, transition_probs, k_neighbors):
    """
    Args:
        velocity: const scl_real_t *
        expression: const scl_real_t *
        knn: struct scl_sparse_matrix *
        n_cells: long
        n_genes: long
        transition_probs: scl_real_t *
        k_neighbors: long
    
    Returns:
        int
    """
    return _lib.scl_velocity_graph(velocity, expression, knn, n_cells, n_genes, transition_probs, k_neighbors)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_velocity_compute",
    "scl_velocity_fit_kinetics",
    "scl_velocity_graph",
    "scl_velocity_model_t",
    "scl_velocity_model_t",
    "scl_velocity_model_t",
    "scl_velocity_splice_ratio",
]