"""
Auto-generated Python bindings for effect_size

Source: scl/binding/c_api/stat/effect_size.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_effect_size_type_t:
    """C enum: scl_effect_size_type_t"""
    SCL_EFFECT_SIZE_COHENS_D = 0
    SCL_EFFECT_SIZE_HEDGES_G = 1
    SCL_EFFECT_SIZE_GLASS_DELTA = 2
    SCL_EFFECT_SIZE_CLES = 3

class scl_effect_size_type_t:
    """C enum: scl_effect_size_type_t"""
    SCL_EFFECT_SIZE_COHENS_D = 0
    SCL_EFFECT_SIZE_HEDGES_G = 1
    SCL_EFFECT_SIZE_GLASS_DELTA = 2
    SCL_EFFECT_SIZE_CLES = 3

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_effect_size_type_t = c_void_p  # typedef enum scl_effect_size_type_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_stat_effect_size(struct scl_sparse_matrix * matrix, const int32_t * group_ids, scl_real_t * out_effect_size, long primary_dim, scl_effect_size_type_t type)
_lib.scl_stat_effect_size.argtypes = [POINTER(c_void_p), POINTER(c_int32), POINTER(c_double), c_long, c_void_p]
_lib.scl_stat_effect_size.restype = c_int

def scl_stat_effect_size(matrix, group_ids, out_effect_size, primary_dim, type):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        out_effect_size: scl_real_t *
        primary_dim: long
        type: scl_effect_size_type_t
    
    Returns:
        int
    """
    return _lib.scl_stat_effect_size(matrix, group_ids, out_effect_size, primary_dim, type)


# C: int scl_stat_ttest_with_effect_size(struct scl_sparse_matrix * matrix, const int32_t * group_ids, scl_real_t * out_t_stats, scl_real_t * out_p_values, scl_real_t * out_log2_fc, scl_real_t * out_effect_size, long primary_dim, scl_effect_size_type_t es_type, int use_welch)
_lib.scl_stat_ttest_with_effect_size.argtypes = [POINTER(c_void_p), POINTER(c_int32), POINTER(c_double), POINTER(c_double), POINTER(c_double), POINTER(c_double), c_long, c_void_p, c_int]
_lib.scl_stat_ttest_with_effect_size.restype = c_int

def scl_stat_ttest_with_effect_size(matrix, group_ids, out_t_stats, out_p_values, out_log2_fc, out_effect_size, primary_dim, es_type, use_welch):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        out_t_stats: scl_real_t *
        out_p_values: scl_real_t *
        out_log2_fc: scl_real_t *
        out_effect_size: scl_real_t *
        primary_dim: long
        es_type: scl_effect_size_type_t
        use_welch: int
    
    Returns:
        int
    """
    return _lib.scl_stat_ttest_with_effect_size(matrix, group_ids, out_t_stats, out_p_values, out_log2_fc, out_effect_size, primary_dim, es_type, use_welch)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_effect_size_type_t",
    "scl_effect_size_type_t",
    "scl_effect_size_type_t",
    "scl_stat_effect_size",
    "scl_stat_ttest_with_effect_size",
]