"""
Auto-generated Python bindings for ks

Source: scl/binding/c_api/stat/ks.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_stat_ks_test(struct scl_sparse_matrix * matrix, const int32_t * group_ids, int n_samples, scl_real_t * D_stats, scl_real_t * p_values, int n_features)
_lib.scl_stat_ks_test.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, POINTER(c_double), POINTER(c_double), c_int]
_lib.scl_stat_ks_test.restype = c_int

def scl_stat_ks_test(matrix, group_ids, n_samples, D_stats, p_values, n_features):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        n_samples: int
        D_stats: scl_real_t *
        p_values: scl_real_t *
        n_features: int
    
    Returns:
        int
    """
    return _lib.scl_stat_ks_test(matrix, group_ids, n_samples, D_stats, p_values, n_features)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_stat_ks_test",
]