"""
Auto-generated Python bindings for permutation_stat

Source: scl/binding/c_api/stat/permutation_stat.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Enums
# ===========================================================================

class scl_perm_stat_type_t:
    """C enum: scl_perm_stat_type_t"""
    SCL_PERM_STAT_MWU = 0
    SCL_PERM_STAT_MEAN_DIFF = 1
    SCL_PERM_STAT_KS = 2

class scl_perm_stat_type_t:
    """C enum: scl_perm_stat_type_t"""
    SCL_PERM_STAT_MWU = 0
    SCL_PERM_STAT_MEAN_DIFF = 1
    SCL_PERM_STAT_KS = 2

# ===========================================================================
# Type Aliases
# ===========================================================================

scl_perm_stat_type_t = c_void_p  # typedef enum scl_perm_stat_type_t


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_stat_batch_permutation(struct scl_sparse_matrix * matrix, const int32_t * group_ids, int n_samples, scl_real_t * p_values, int n_features, int n_permutations, scl_perm_stat_type_t stat_type, unsigned long seed)
_lib.scl_stat_batch_permutation.argtypes = [POINTER(c_void_p), POINTER(c_int32), c_int, POINTER(c_double), c_int, c_int, c_void_p, c_ulong]
_lib.scl_stat_batch_permutation.restype = c_int

def scl_stat_batch_permutation(matrix, group_ids, n_samples, p_values, n_features, n_permutations, stat_type, seed):
    """
    Args:
        matrix: struct scl_sparse_matrix *
        group_ids: const int32_t *
        n_samples: int
        p_values: scl_real_t *
        n_features: int
        n_permutations: int
        stat_type: scl_perm_stat_type_t
        seed: unsigned long
    
    Returns:
        int
    """
    return _lib.scl_stat_batch_permutation(matrix, group_ids, n_samples, p_values, n_features, n_permutations, stat_type, seed)


# C: int scl_stat_permutation_single(const scl_real_t * values, int n_samples, const int32_t * group_ids, int n_permutations, scl_perm_stat_type_t stat_type, unsigned long seed, scl_real_t * p_value_out)
_lib.scl_stat_permutation_single.argtypes = [POINTER(c_double), c_int, POINTER(c_int32), c_int, c_void_p, c_ulong, POINTER(c_double)]
_lib.scl_stat_permutation_single.restype = c_int

def scl_stat_permutation_single(values, n_samples, group_ids, n_permutations, stat_type, seed, p_value_out):
    """
    Args:
        values: const scl_real_t *
        n_samples: int
        group_ids: const int32_t *
        n_permutations: int
        stat_type: scl_perm_stat_type_t
        seed: unsigned long
        p_value_out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_stat_permutation_single(values, n_samples, group_ids, n_permutations, stat_type, seed, p_value_out)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_perm_stat_type_t",
    "scl_perm_stat_type_t",
    "scl_perm_stat_type_t",
    "scl_stat_batch_permutation",
    "scl_stat_permutation_single",
]