import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'SCL Core',
  description: 'High-performance biological operator library',

  lang: 'en-US',

  // Ignore dead links for pages that will be generated by codegen
  ignoreDeadLinks: true,

  head: [
    ['link', { rel: 'icon', href: '/favicon.ico' }],
  ],

  markdown: {
    math: true,
    lineNumbers: true,
    theme: {
      light: 'github-light',
      dark: 'github-dark'
    }
  },

  themeConfig: {
    logo: '/logo.svg',

    nav: [
      { text: 'Home', link: '/' },
      { text: 'C++ API', link: '/cpp/' },
      { text: 'C API', link: '/api/c-api/' },
      { text: 'Python API', link: '/python/' },
    ],

    sidebar: {
      '/cpp/': [
        {
          text: 'C++ API',
          items: [
            { text: 'Overview', link: '/cpp/' },
          ]
        }
      ],
      '/api/c-api/': [
        {
          text: 'C API Reference',
          items: [
            { text: 'Overview', link: '/api/c-api/' },
          ]
        },
        {
          text: 'Core',
          collapsed: false,
          items: [
            { text: 'core', link: '/api/c-api/core' },
            { text: 'sparse', link: '/api/c-api/sparse' },
            { text: 'dense', link: '/api/c-api/dense' },
          ]
        },
        {
          text: 'Linear Algebra',
          collapsed: false,
          items: [
            { text: 'algebra', link: '/api/c-api/algebra' },
          ]
        },
        {
          text: 'Preprocessing',
          collapsed: true,
          items: [
            { text: 'normalize', link: '/api/c-api/normalize' },
            { text: 'scale', link: '/api/c-api/scale' },
            { text: 'log1p', link: '/api/c-api/log1p' },
          ]
        },
        {
          text: 'Clustering',
          collapsed: true,
          items: [
            { text: 'leiden', link: '/api/c-api/leiden' },
            { text: 'louvain', link: '/api/c-api/louvain' },
          ]
        },
        {
          text: 'Statistics',
          collapsed: true,
          items: [
            { text: 'ttest', link: '/api/c-api/ttest' },
            { text: 'mwu', link: '/api/c-api/mwu' },
            { text: 'auroc', link: '/api/c-api/auroc' },
          ]
        }
      ],
      '/python/': [
        {
          text: 'Python API',
          items: [
            { text: 'Overview', link: '/python/' },
          ]
        }
      ]
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/krkawzq/scl-core' }
    ],

    search: {
      provider: 'local'
    },

    outline: {
      level: [2, 3],
      label: 'On this page'
    },

    lastUpdated: {
      text: 'Last updated',
      formatOptions: {
        dateStyle: 'short',
        timeStyle: 'short'
      }
    }
  }
})
