#!/bin/bash
#
# Multi-Platform Slice Strategy Simulation
# Generates optimized strategy code for different hardware platforms
#
# Usage: ./run_multiplatform_simulation.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/../../scl/strategy"

echo "=========================================="
echo "Multi-Platform Slice Strategy Simulation"
echo "=========================================="
echo ""

# =============================================================================
# Platform Configurations (based on real hardware specs)
# =============================================================================

# x86_64 AVX-512 (Skylake-X, Ice Lake, Sapphire Rapids)
# - L1: 32KB, 4 cycles
# - L2: 1MB, 12 cycles  
# - L3: 16MB, 40 cycles
# - DRAM: 200 cycles
# - SIMD: 512-bit (64 bytes)
# - Branch penalty: 15-20 cycles
run_avx512() {
    echo "=== Platform: x86_64 AVX-512 ==="
    python3 "$SCRIPT_DIR/slice_simulator.py" \
        --generate-code \
        --output "$OUTPUT_DIR/slice_strategy_avx512.hpp" \
        --cache-l1 32768 \
        --cache-l2 1048576 \
        --cache-l3 16777216 \
        --latency-l1 4.0 \
        --latency-l2 12.0 \
        --latency-l3 40.0 \
        --latency-dram 200.0 \
        --simd-width 64 \
        --branch-penalty 17.5
    echo ""
}

# x86_64 AVX2 (Haswell, Broadwell, Skylake, Zen 2/3)
# - L1: 32KB, 4 cycles
# - L2: 256KB, 12 cycles
# - L3: 8MB, 40 cycles
# - DRAM: 200 cycles
# - SIMD: 256-bit (32 bytes)
# - Branch penalty: 15 cycles
run_avx2() {
    echo "=== Platform: x86_64 AVX2 ==="
    python3 "$SCRIPT_DIR/slice_simulator.py" \
        --generate-code \
        --output "$OUTPUT_DIR/slice_strategy_avx2.hpp" \
        --cache-l1 32768 \
        --cache-l2 262144 \
        --cache-l3 8388608 \
        --latency-l1 4.0 \
        --latency-l2 12.0 \
        --latency-l3 40.0 \
        --latency-dram 200.0 \
        --simd-width 32 \
        --branch-penalty 15.0
    echo ""
}

# x86_64 SSE2 (Legacy x86_64, all 64-bit x86)
# - L1: 32KB, 3 cycles
# - L2: 256KB, 14 cycles
# - L3: 4MB, 50 cycles
# - DRAM: 220 cycles
# - SIMD: 128-bit (16 bytes)
# - Branch penalty: 18 cycles
run_sse2() {
    echo "=== Platform: x86_64 SSE2 ==="
    python3 "$SCRIPT_DIR/slice_simulator.py" \
        --generate-code \
        --output "$OUTPUT_DIR/slice_strategy_sse2.hpp" \
        --cache-l1 32768 \
        --cache-l2 262144 \
        --cache-l3 4194304 \
        --latency-l1 3.0 \
        --latency-l2 14.0 \
        --latency-l3 50.0 \
        --latency-dram 220.0 \
        --simd-width 16 \
        --branch-penalty 18.0
    echo ""
}

# ARM64 NEON (Cortex-A72, A76, Apple M1/M2)
# - L1: 64KB, 3 cycles (ARM typically larger L1)
# - L2: 4MB, 15 cycles
# - L3: varies, 30 cycles (unified or system-level)
# - DRAM: 180 cycles (better memory controller)
# - SIMD: 128-bit (16 bytes)
# - Branch penalty: 12 cycles (better prediction)
run_neon() {
    echo "=== Platform: ARM64 NEON ==="
    python3 "$SCRIPT_DIR/slice_simulator.py" \
        --generate-code \
        --output "$OUTPUT_DIR/slice_strategy_neon.hpp" \
        --cache-l1 65536 \
        --cache-l2 4194304 \
        --cache-l3 8388608 \
        --latency-l1 3.0 \
        --latency-l2 15.0 \
        --latency-l3 30.0 \
        --latency-dram 180.0 \
        --simd-width 16 \
        --branch-penalty 12.0
    echo ""
}

# Scalar fallback (no SIMD)
# - Conservative cache parameters
# - Higher branch penalty (no prediction)
run_scalar() {
    echo "=== Platform: Scalar (No SIMD) ==="
    python3 "$SCRIPT_DIR/slice_simulator.py" \
        --generate-code \
        --output "$OUTPUT_DIR/slice_strategy_scalar.hpp" \
        --cache-l1 32768 \
        --cache-l2 262144 \
        --cache-l3 4194304 \
        --latency-l1 4.0 \
        --latency-l2 15.0 \
        --latency-l3 50.0 \
        --latency-dram 220.0 \
        --simd-width 8 \
        --branch-penalty 20.0
    echo ""
}

# =============================================================================
# Run Simulations
# =============================================================================

echo "Generating platform-specific strategy code..."
echo ""

# Create output directory if needed
mkdir -p "$OUTPUT_DIR"

# Run all platform simulations
run_avx512
run_avx2
run_sse2
run_neon
run_scalar

# Generate unified dispatch header
echo "=== Generating Unified Dispatch Header ==="
cat > "$OUTPUT_DIR/slice_strategy.hpp" << 'EOF'
#pragma once

/// @file scl/sparse/slice_strategy.hpp
/// @brief Platform-Adaptive Strategy Selection for Sparse Slice Operations
///
/// This header automatically includes the platform-specific strategy
/// implementation based on compile-time SIMD feature detection.
///
/// Generated by: run_multiplatform_simulation.sh
///
/// Supported Platforms:
///   - x86_64 AVX-512: Skylake-X, Ice Lake, Sapphire Rapids
///   - x86_64 AVX2: Haswell, Broadwell, Skylake, Zen 2/3/4
///   - x86_64 SSE2: All 64-bit x86 processors
///   - ARM64 NEON: Cortex-A series, Apple Silicon
///   - Scalar: Fallback for any architecture

#include "scl/core/macro.hpp"

// Platform-specific strategy selection
#if SCL_SIMD_AVX512
    #include "scl/sparse/slice_strategy_avx512.hpp"
#elif SCL_SIMD_AVX2
    #include "scl/sparse/slice_strategy_avx2.hpp"
#elif SCL_SIMD_SSE2
    #include "scl/sparse/slice_strategy_sse2.hpp"
#elif SCL_SIMD_NEON
    #include "scl/sparse/slice_strategy_neon.hpp"
#else
    #include "scl/sparse/slice_strategy_scalar.hpp"
#endif

// The platform-specific header defines:
//   - scl::sparse::SliceStrategy enum
//   - scl::sparse::select_slice_strategy(p, m) function
//   - scl::sparse::strategy_name(strategy) function
EOF

echo "Generated: $OUTPUT_DIR/slice_strategy.hpp"
echo ""

echo "=========================================="
echo "Simulation Complete!"
echo "=========================================="
echo ""
echo "Generated files:"
echo "  - slice_strategy.hpp (unified dispatch)"
echo "  - slice_strategy_avx512.hpp"
echo "  - slice_strategy_avx2.hpp"
echo "  - slice_strategy_sse2.hpp"
echo "  - slice_strategy_neon.hpp"
echo "  - slice_strategy_scalar.hpp"
echo ""

