#pragma once

// =============================================================================
// FILE: scl/kernel/core.hpp
// BRIEF: Unified include file for all kernel implementations
// =============================================================================

// Core kernel implementations
#include "scl/kernel/algebra.hpp"
#include "scl/kernel/alignment.hpp"
#include "scl/kernel/annotation.hpp"
#include "scl/kernel/association.hpp"
#include "scl/kernel/bbknn.hpp"
#include "scl/kernel/centrality.hpp"
#include "scl/kernel/clonotype.hpp"
#include "scl/kernel/coexpression.hpp"
#include "scl/kernel/communication.hpp"
#include "scl/kernel/comparison.hpp"
#include "scl/kernel/components.hpp"
#include "scl/kernel/correlation.hpp"
#include "scl/kernel/diffusion.hpp"
#include "scl/kernel/doublet.hpp"
#include "scl/kernel/enrichment.hpp"
#include "scl/kernel/entropy.hpp"
#include "scl/kernel/feature.hpp"
#include "scl/kernel/gnn.hpp"
#include "scl/kernel/gram.hpp"
#include "scl/kernel/grn.hpp"
#include "scl/kernel/group.hpp"
#include "scl/kernel/hotspot.hpp"
#include "scl/kernel/hvg.hpp"
#include "scl/kernel/impute.hpp"
#include "scl/kernel/kernel.hpp"
#include "scl/kernel/leiden.hpp"
#include "scl/kernel/lineage.hpp"
#include "scl/kernel/log1p.hpp"
#include "scl/kernel/louvain.hpp"
#include "scl/kernel/markers.hpp"
#include "scl/kernel/merge.hpp"
#include "scl/kernel/metrics.hpp"
#include "scl/kernel/mmd.hpp"
#include "scl/kernel/multiple_testing.hpp"
#include "scl/kernel/mwu.hpp"
#include "scl/kernel/neighbors.hpp"
#include "scl/kernel/niche.hpp"
#include "scl/kernel/normalize.hpp"
#include "scl/kernel/outlier.hpp"
#include "scl/kernel/permutation.hpp"
#include "scl/kernel/projection.hpp"
#include "scl/kernel/propagation.hpp"
#include "scl/kernel/pseudotime.hpp"
#include "scl/kernel/qc.hpp"
#include "scl/kernel/reorder.hpp"
#include "scl/kernel/resample.hpp"
#include "scl/kernel/sampling.hpp"
#include "scl/kernel/scale.hpp"
#include "scl/kernel/scoring.hpp"
#include "scl/kernel/slice.hpp"
#include "scl/kernel/softmax.hpp"
#include "scl/kernel/sparse.hpp"
#include "scl/kernel/sparse_opt.hpp"
#include "scl/kernel/spatial.hpp"
#include "scl/kernel/spatial_pattern.hpp"
#include "scl/kernel/state.hpp"
#include "scl/kernel/subpopulation.hpp"
#include "scl/kernel/tissue.hpp"
#include "scl/kernel/transition.hpp"
#include "scl/kernel/ttest.hpp"
#include "scl/kernel/velocity.hpp"

// Statistical kernel implementations
#include "scl/kernel/stat/auroc.hpp"
#include "scl/kernel/stat/effect_size.hpp"
#include "scl/kernel/stat/group_partition.hpp"
#include "scl/kernel/stat/kruskal_wallis.hpp"
#include "scl/kernel/stat/ks.hpp"
#include "scl/kernel/stat/oneway_anova.hpp"
#include "scl/kernel/stat/permutation_stat.hpp"
#include "scl/kernel/stat/rank_utils.hpp"
#include "scl/kernel/stat/stat_base.hpp"

