#pragma once

/// @file sparse_slice_strategy.hpp
/// @brief Optimized Strategy Selection for Sparse Matrix Slice Operations
///
/// Auto-generated by slice_simulator.py
/// 
/// Strategy Distribution (based on cost model):
///   - SKIP:  0.0%
///   - PROBE: 91.7%
///   - MERGE: 7.9%
///   - RANGE: 0.4%
///
/// Key Insight: Real sparse matrices have p < 0.1 in 90%+ cases

#include <cstdint>

#include "scl/core/macro.hpp"
#include "scl/core/platform.hpp"

namespace scl::sparse {

/// @brief Processing strategy for sparse slice operations
enum class SliceStrategy : std::int8_t {
    SKIP  = -1, ///< Segment-level pruning (no overlap)
    PROBE = 0,  ///< Point-wise probing (A)
    MERGE = 1,  ///< Two-pointer merge (B)
    RANGE = 2   ///< Range query with RLE (C)
};

/// @brief Select optimal strategy with segment-level pruning
/// @param[in] p Estimated density (fraction of non-zeros)
/// @param[in] m Segment size (number of indices)
/// @param[in] i_min Minimum index in segment
/// @param[in] i_max Maximum index in segment
/// @param[in] mask_min First nonzero position in mask
/// @param[in] mask_max Last nonzero position in mask
/// @return Optimal strategy
///
/// ## Performance Characteristics
///
/// This function is optimized for typical sparse matrix distributions:
/// - 90%+ cases: p < 0.1 (very sparse)
/// - Branch hints reflect real-world usage patterns
/// - Zero table lookup overhead
/// - Segment-level pruning for disjoint ranges
///
/// ## Decision Logic
///
/// ```
/// # Step 1: Segment-level pruning (GraphBLAS Case 1-4)
/// if i_max < mask_min or i_min > mask_max:
///     return SKIP
///
/// # Step 2: Strategy selection based on density
/// if p < 0.1:      # Most common (90%+)
///     if m < 100:  # Small segments
///         PROBE
///     else:
///         PROBE if m < 50/p else MERGE
/// elif p < 0.5:    # Medium density (rare)
///     MERGE
/// else:            # High density (should use dense!)
///     MERGE or RANGE
/// ```
template<typename Index>
[[nodiscard]]
SCL_FORCE_INLINE
constexpr
auto select_slice_strategy(
    float p, 
    Index m,
    Index i_min, 
    Index i_max,
    Index mask_min,
    Index mask_max
) noexcept -> SliceStrategy {
    // Step 1: Segment-level range pruning
    // GraphBLAS fast path: completely disjoint ranges
    if (m == 0 || i_max < mask_min || i_min > mask_max) [[unlikely]] {
        return SliceStrategy::SKIP;
    }
    
    // Step 2: Fast path for typical sparse matrices (p < 0.1)
    // This covers 90%+ of real-world sparse matrix operations
    if (p < 0.1f) [[likely]] {
        // Very small segments: always probe
        if (m < 100) [[likely]] {
            return SliceStrategy::PROBE;
        }
        
        // Transition point based on density-size trade-off
        // As density increases, prefer merge earlier
        const int threshold = static_cast<int>(50.0f / p);
        return (m < threshold) ? SliceStrategy::PROBE : SliceStrategy::MERGE;
    }
    
    // Medium density (0.1 <= p < 0.5) - less common
    // MERGE is almost always optimal in this range
    if (p < 0.5f) [[likely]] {
        return SliceStrategy::MERGE;
    }
    
    // High density (p >= 0.5) - should rarely happen!
    // If we reach here, the user should reconsider using sparse format
    [[unlikely]] {
        // Extreme case: very high density + huge segment
        // Consider RANGE strategy with RLE compression
        if (p > 0.9f && m > 50000) [[unlikely]] {
            return SliceStrategy::RANGE;
        }
        
        // Otherwise, MERGE is still reasonable
        return SliceStrategy::MERGE;
    }
}

/// @brief Get strategy name for debugging
[[nodiscard]]
constexpr
auto strategy_name(SliceStrategy s) noexcept -> const char* {
    switch (s) {
        case SliceStrategy::SKIP:  return "SKIP";
        case SliceStrategy::PROBE: return "PROBE";
        case SliceStrategy::MERGE: return "MERGE";
        case SliceStrategy::RANGE: return "RANGE";
        default: return "UNKNOWN";
    }
}

}  // namespace scl::sparse
