#pragma once

/// @file scl/sparse/slice_strategy.hpp
/// @brief Platform-Adaptive Strategy Selection for Sparse Slice Operations
///
/// This header automatically includes the platform-specific strategy
/// implementation based on compile-time SIMD feature detection.
///
/// Generated by: run_multiplatform_simulation.sh
///
/// Supported Platforms:
///   - x86_64 AVX-512: Skylake-X, Ice Lake, Sapphire Rapids
///   - x86_64 AVX2: Haswell, Broadwell, Skylake, Zen 2/3/4
///   - x86_64 SSE2: All 64-bit x86 processors
///   - ARM64 NEON: Cortex-A series, Apple Silicon
///   - Scalar: Fallback for any architecture

#include "scl/core/macro.hpp"

// Platform-specific strategy selection
#if SCL_SIMD_AVX512
    #include "scl/strategy/slice_strategy_avx512.hpp"
#elif SCL_SIMD_AVX2
    #include "scl/strategy/slice_strategy_avx2.hpp"
#elif SCL_SIMD_SSE2
    #include "scl/strategy/slice_strategy_sse2.hpp"
#elif SCL_SIMD_NEON
    #include "scl/strategy/slice_strategy_neon.hpp"
#else
    #include "scl/strategy/slice_strategy_scalar.hpp"
#endif

// The platform-specific header defines:
//   - scl::sparse::SliceStrategy enum
//   - scl::sparse::select_slice_strategy(p, m) function
//   - scl::sparse::strategy_name(strategy) function
