#pragma once

/// @file sparse_slice_strategy.hpp
/// @brief Optimized Strategy Selection for Sparse Matrix Slice Operations
///
/// Auto-generated by slice_simulator.py from cost model analysis
/// 
/// Strategy Distribution (based on cost model):
///   - SKIP:  0.0%
///   - PROBE: 85.5%
///   - MERGE: 14.0%
///   - RANGE: 0.5%
///
/// Platform-specific thresholds (fitted from LUT):
///   - Threshold function: m_threshold(p) = -765.78 / p + 7532.05
///   - Fit quality: good (R² = 0.8678)
///
/// Key Insight: Real sparse matrices have p < 0.1 in 90%+ cases

#include <cstdint>

#include "scl/core/macro.hpp"

namespace scl::sparse {

/// @brief Processing strategy for sparse slice operations
enum class SliceStrategy : std::int8_t {
    SKIP  = -1, ///< Segment-level pruning (no overlap)
    PROBE = 0,  ///< Point-wise probing (A)
    MERGE = 1,  ///< Two-pointer merge (B)
    RANGE = 2   ///< Range query with RLE (C)
};

/// @brief Select optimal strategy with segment-level pruning
/// @param[in] p Estimated density (fraction of non-zeros)
/// @param[in] m Segment size (number of indices)
/// @param[in] i_min Minimum index in segment
/// @param[in] i_max Maximum index in segment
/// @param[in] mask_min First nonzero position in mask
/// @param[in] mask_max Last nonzero position in mask
/// @return Optimal strategy
///
/// ## Implementation
///
/// Pure branch-based decision (no memory access, no lookup tables).
/// Thresholds are platform-specific, fitted from cost model simulation.
///
/// ## Decision Logic
///
/// 1. Segment-level pruning: Skip if ranges disjoint
/// 2. Density-based strategy selection with platform-tuned thresholds
template<typename Index>
[[nodiscard]]
SCL_FORCE_INLINE
constexpr
auto select_slice_strategy(
    float p, 
    Index m,
    Index i_min, 
    Index i_max,
    Index mask_min,
    Index mask_max
) noexcept -> SliceStrategy {
    // Step 1: Segment-level range pruning
    if (m == 0 || i_max < mask_min || i_min > mask_max) [[unlikely]] {
        return SliceStrategy::SKIP;
    }
    
    // Step 2: Strategy selection (platform-tuned thresholds)
    // Fast path: typical sparse matrices (p < 0.1)
    if (p < 0.1f) [[likely]] {
        // Very small segments: always probe
        if (m < 100) [[likely]] {
            return SliceStrategy::PROBE;
        }
        
        // Platform-specific transition point (fitted from cost model)
        const float threshold = -765.78f / p + 7532.05f;
        return (static_cast<float>(m) < threshold) ? SliceStrategy::PROBE : SliceStrategy::MERGE;
    }
    
    // Medium density (0.1 <= p < 0.5)
    if (p < 0.5f) [[likely]] {
        return SliceStrategy::MERGE;
    }
    
    // High density (p >= 0.5) - rare case
    [[unlikely]] {
        // Extreme case: very high density + huge segment
        if (p > 0.9f && m > 50000) [[unlikely]] {
            return SliceStrategy::RANGE;
        }
        return SliceStrategy::MERGE;
    }
}

/// @brief Simplified strategy selection (no range pruning)
/// @param[in] p Estimated density
/// @param[in] m Segment size
/// @return Optimal strategy
template<typename Index>
[[nodiscard]]
SCL_FORCE_INLINE
constexpr
auto select_slice_strategy(float p, Index m) noexcept -> SliceStrategy {
    if (p < 0.1f) [[likely]] {
        if (m < 100) [[likely]] {
            return SliceStrategy::PROBE;
        }
        const float threshold = -765.78f / p + 7532.05f;
        return (static_cast<float>(m) < threshold) ? SliceStrategy::PROBE : SliceStrategy::MERGE;
    }
    
    if (p < 0.5f) [[likely]] {
        return SliceStrategy::MERGE;
    }
    
    return SliceStrategy::MERGE;
}

/// @brief Get strategy name for debugging
[[nodiscard]]
constexpr
auto strategy_name(SliceStrategy s) noexcept -> const char* {
    switch (s) {
        case SliceStrategy::SKIP:  return "SKIP";
        case SliceStrategy::PROBE: return "PROBE";
        case SliceStrategy::MERGE: return "MERGE";
        case SliceStrategy::RANGE: return "RANGE";
        default: return "UNKNOWN";
    }
}

}  // namespace scl::sparse
