"""
Auto-generated Python bindings for dense

Source: scl/binding/c_api/core/dense.h
Generated by: generate_bindings.py

DO NOT EDIT - This file is automatically generated.
"""

from __future__ import annotations

from ctypes import (
    CFUNCTYPE,
    POINTER,
    Structure,
    c_bool,
    c_char,
    c_char_p,
    c_double,
    c_float,
    c_int,
    c_int8,
    c_int16,
    c_int32,
    c_int64,
    c_long,
    c_longlong,
    c_short,
    c_size_t,
    c_ssize_t,
    c_ubyte,
    c_uint,
    c_uint8,
    c_uint16,
    c_uint32,
    c_uint64,
    c_ulong,
    c_ulonglong,
    c_ushort,
    c_void_p,
    c_wchar_p,
)
from typing import Any, Optional

from .._loader import get_library

# Load the native library
_lib = get_library()


# ===========================================================================
# Functions
# ===========================================================================

# C: int scl_dense_wrap(scl_dense_t * out, long rows, long cols, scl_real_t * data, long stride)
_lib.scl_dense_wrap.argtypes = [POINTER(POINTER(scl_dense_matrix)), c_long, c_long, POINTER(c_double), c_long]
_lib.scl_dense_wrap.restype = c_int

def scl_dense_wrap(out, rows, cols, data, stride):
    """
     @brief Create view wrapping external data (zero-copy, does not own data)
 @param[out] out Output view handle (non-null)
 @param[in] rows Number of rows (> 0)
 @param[in] cols Number of columns (> 0)
 @param[in,out] data Mutable data pointer (non-null, caller manages lifetime)
 @param[in] stride Row stride (>= cols, usually equals cols for contiguous)
 @return SCL_OK on success, error code otherwise
 @note Does NOT copy or own data - caller must keep data alive
 @note Stride allows non-contiguous sub-matrices
 @note Caller must call scl_dense_destroy() when done (frees handle only)
    
    Args:
        out: scl_dense_t *
        rows: long
        cols: long
        data: scl_real_t *
        stride: long
    
    Returns:
        int
    """
    return _lib.scl_dense_wrap(out, rows, cols, data, stride)


# C: int scl_dense_destroy(scl_dense_t * matrix)
_lib.scl_dense_destroy.argtypes = [POINTER(POINTER(scl_dense_matrix))]
_lib.scl_dense_destroy.restype = c_int

def scl_dense_destroy(matrix):
    """
     @brief Destroy dense view and release handle
 @param[in,out] matrix Pointer to view handle (may be null)
 @return SCL_OK on success, error code otherwise
 @note Sets *matrix to NULL after destruction
 @note Safe to call with NULL or already-destroyed handle
 @note Does NOT free the underlying data (view only)
    
    Args:
        matrix: scl_dense_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_destroy(matrix)


# C: int scl_dense_rows(struct scl_dense_matrix * matrix, scl_index_t * out)
_lib.scl_dense_rows.argtypes = [POINTER(c_void_p), POINTER(c_int64)]
_lib.scl_dense_rows.restype = c_int

def scl_dense_rows(matrix, out):
    """
     @brief Get number of rows
 @param[in] matrix View handle (non-null)
 @param[out] out Number of rows (non-null)
 @return SCL_OK on success, error code otherwise
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_rows(matrix, out)


# C: int scl_dense_cols(struct scl_dense_matrix * matrix, scl_index_t * out)
_lib.scl_dense_cols.argtypes = [POINTER(c_void_p), POINTER(c_int64)]
_lib.scl_dense_cols.restype = c_int

def scl_dense_cols(matrix, out):
    """
     @brief Get number of columns
 @param[in] matrix View handle (non-null)
 @param[out] out Number of columns (non-null)
 @return SCL_OK on success, error code otherwise
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_cols(matrix, out)


# C: int scl_dense_stride(struct scl_dense_matrix * matrix, scl_index_t * out)
_lib.scl_dense_stride.argtypes = [POINTER(c_void_p), POINTER(c_int64)]
_lib.scl_dense_stride.restype = c_int

def scl_dense_stride(matrix, out):
    """
     @brief Get row stride
 @param[in] matrix View handle (non-null)
 @param[out] out Row stride (non-null)
 @return SCL_OK on success, error code otherwise
 @note Stride is distance between consecutive rows
 @note For contiguous matrices: stride == cols
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_index_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_stride(matrix, out)


# C: int scl_dense_size(struct scl_dense_matrix * matrix, scl_size_t * out)
_lib.scl_dense_size.argtypes = [POINTER(c_void_p), POINTER(c_int)]
_lib.scl_dense_size.restype = c_int

def scl_dense_size(matrix, out):
    """
     @brief Get total number of elements
 @param[in] matrix View handle (non-null)
 @param[out] out Total elements = rows * cols (non-null)
 @return SCL_OK on success, error code otherwise
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_size_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_size(matrix, out)


# C: int scl_dense_is_valid(struct scl_dense_matrix * matrix, scl_bool_t * out)
_lib.scl_dense_is_valid.argtypes = [POINTER(c_void_p), POINTER(c_int)]
_lib.scl_dense_is_valid.restype = c_int

def scl_dense_is_valid(matrix, out):
    """
     @brief Check if view is in valid state
 @param[in] matrix View handle (non-null)
 @param[out] out SCL_TRUE if valid, SCL_FALSE otherwise (non-null)
 @return SCL_OK on success, error code otherwise
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_bool_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_is_valid(matrix, out)


# C: int scl_dense_is_contiguous(struct scl_dense_matrix * matrix, scl_bool_t * out)
_lib.scl_dense_is_contiguous.argtypes = [POINTER(c_void_p), POINTER(c_int)]
_lib.scl_dense_is_contiguous.restype = c_int

def scl_dense_is_contiguous(matrix, out):
    """
     @brief Check if view is contiguous (stride == cols)
 @param[in] matrix View handle (non-null)
 @param[out] out SCL_TRUE if contiguous, SCL_FALSE otherwise (non-null)
 @return SCL_OK on success, error code otherwise
    
    Args:
        matrix: struct scl_dense_matrix *
        out: scl_bool_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_is_contiguous(matrix, out)


# C: int scl_dense_get_data(struct scl_dense_matrix * matrix, const scl_real_t ** out, scl_size_t * size)
_lib.scl_dense_get_data.argtypes = [POINTER(c_void_p), POINTER(POINTER(c_double)), POINTER(c_int)]
_lib.scl_dense_get_data.restype = c_int

def scl_dense_get_data(matrix, out, size):
    """
     @brief Get pointer to internal data
 @param[in] matrix View handle (non-null)
 @param[out] out Pointer to data (non-null)
 @param[out] size Total accessible elements = rows * stride (non-null)
 @return SCL_OK on success, error code otherwise
 @note Returned pointer valid while underlying data alive
 @note For non-contiguous views, use stride to access elements correctly
    
    Args:
        matrix: struct scl_dense_matrix *
        out: const scl_real_t **
        size: scl_size_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_get_data(matrix, out, size)


# C: int scl_dense_get(struct scl_dense_matrix * matrix, long row, long col, scl_real_t * out)
_lib.scl_dense_get.argtypes = [POINTER(c_void_p), c_long, c_long, POINTER(c_double)]
_lib.scl_dense_get.restype = c_int

def scl_dense_get(matrix, row, col, out):
    """
     @brief Get element at (row, col)
 @param[in] matrix View handle (non-null)
 @param[in] row Row index [0, rows)
 @param[in] col Column index [0, cols)
 @param[out] out Element value (non-null)
 @return SCL_OK on success, error code otherwise
 @note Returns SCL_ERROR_INDEX_OUT_OF_BOUNDS if indices invalid
    
    Args:
        matrix: struct scl_dense_matrix *
        row: long
        col: long
        out: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_get(matrix, row, col, out)


# C: int scl_dense_set(struct scl_dense_matrix * matrix, long row, long col, double value)
_lib.scl_dense_set.argtypes = [POINTER(c_void_p), c_long, c_long, c_double]
_lib.scl_dense_set.restype = c_int

def scl_dense_set(matrix, row, col, value):
    """
     @brief Set element at (row, col)
 @param[in] matrix View handle (non-null)
 @param[in] row Row index [0, rows)
 @param[in] col Column index [0, cols)
 @param[in] value New element value
 @return SCL_OK on success, error code otherwise
 @note Returns SCL_ERROR_INDEX_OUT_OF_BOUNDS if indices invalid
    
    Args:
        matrix: struct scl_dense_matrix *
        row: long
        col: long
        value: double
    
    Returns:
        int
    """
    return _lib.scl_dense_set(matrix, row, col, value)


# C: int scl_dense_export(struct scl_dense_matrix * matrix, scl_real_t * data)
_lib.scl_dense_export.argtypes = [POINTER(c_void_p), POINTER(c_double)]
_lib.scl_dense_export.restype = c_int

def scl_dense_export(matrix, data):
    """
     @brief Export to caller-allocated buffer (copies data)
 @param[in] matrix View handle (non-null)
 @param[out] data Caller-allocated buffer [rows * cols] (non-null)
 @return SCL_OK on success, error code otherwise
 @note Always copies data in row-major contiguous format
 @note Caller responsible for allocating rows * cols elements
    
    Args:
        matrix: struct scl_dense_matrix *
        data: scl_real_t *
    
    Returns:
        int
    """
    return _lib.scl_dense_export(matrix, data)


# C: int scl_dense_fill(struct scl_dense_matrix * matrix, double value)
_lib.scl_dense_fill.argtypes = [POINTER(c_void_p), c_double]
_lib.scl_dense_fill.restype = c_int

def scl_dense_fill(matrix, value):
    """
     @brief Fill view with scalar value
 @param[in] matrix View handle (non-null)
 @param[in] value Fill value
 @return SCL_OK on success, error code otherwise
 @note Modifies underlying data in-place
    
    Args:
        matrix: struct scl_dense_matrix *
        value: double
    
    Returns:
        int
    """
    return _lib.scl_dense_fill(matrix, value)


# ===========================================================================
# Exports
# ===========================================================================

__all__ = [
    "scl_dense_cols",
    "scl_dense_destroy",
    "scl_dense_export",
    "scl_dense_fill",
    "scl_dense_get",
    "scl_dense_get_data",
    "scl_dense_is_contiguous",
    "scl_dense_is_valid",
    "scl_dense_rows",
    "scl_dense_set",
    "scl_dense_size",
    "scl_dense_stride",
    "scl_dense_wrap",
]